# English (Australia) translation for nova
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the nova package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version:  nova\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2012-02-26 23:03+0000\n"
"PO-Revision-Date: 2011-10-21 11:27+0000\n"
"Last-Translator: Tom Fifield <Unknown>\n"
"Language-Team: English (Australia) <en_AU@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: nova/crypto.py:50
msgid "Filename of root CA"
msgstr "Filename of root CA"

#: nova/crypto.py:53
msgid "Filename of private key"
msgstr "Filename of private key"

#: nova/crypto.py:56
msgid "Filename of root Certificate Revocation List"
msgstr ""

#: nova/crypto.py:59
msgid "Where we keep our keys"
msgstr "Where we keep our keys"

#: nova/crypto.py:62
msgid "Where we keep our root CA"
msgstr "Where we keep our root CA"

#: nova/crypto.py:65
msgid "Should we use a CA for each project?"
msgstr "Should we use a CA for each project?"

#: nova/crypto.py:69
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr "Subject for certificate for users, %s for project, user, timestamp"

#: nova/crypto.py:74
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr "Subject for certificate for projects, %s for project, timestamp"

#: nova/crypto.py:142 nova/crypto.py:159 nova/crypto.py:248
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: nova/crypto.py:307
#, python-format
msgid "Flags path: %s"
msgstr "Flags path: %s"

#: nova/exception.py:56
msgid "Unexpected error while running command."
msgstr "Unexpected error while running command."

#: nova/exception.py:59
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"

#: nova/exception.py:92
msgid "DB exception wrapped."
msgstr ""

#: nova/exception.py:153
msgid "An unknown exception occurred."
msgstr ""

#: nova/exception.py:176
msgid "Failed to decrypt text"
msgstr ""

#: nova/exception.py:180
msgid "Failed to paginate through images from image service"
msgstr ""

#: nova/exception.py:184
msgid "Virtual Interface creation failed"
msgstr ""

#: nova/exception.py:188
msgid "5 attempts to create virtual interfacewith unique mac address failed"
msgstr ""

#: nova/exception.py:193
msgid "Connection to glance failed"
msgstr ""

#: nova/exception.py:197
msgid "Connection to melange failed"
msgstr ""

#: nova/exception.py:201
msgid "Not authorized."
msgstr ""

#: nova/exception.py:206
msgid "User does not have admin privileges"
msgstr ""

#: nova/exception.py:210
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: nova/exception.py:214
msgid "Unacceptable parameters."
msgstr ""

#: nova/exception.py:219
msgid "Invalid snapshot"
msgstr ""

#: nova/exception.py:223
#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr ""

#: nova/exception.py:227 nova/api/openstack/compute/contrib/keypairs.py:103
msgid "Keypair data is invalid"
msgstr ""

#: nova/exception.py:231
msgid "Failed to load data into json format"
msgstr ""

#: nova/exception.py:235
msgid "The request is invalid."
msgstr ""

#: nova/exception.py:239
#, python-format
msgid "Invalid signature %(signature)s for user %(user)s."
msgstr ""

#: nova/exception.py:243
msgid "Invalid input received"
msgstr ""

#: nova/exception.py:247
#, python-format
msgid "Invalid instance type %(instance_type)s."
msgstr ""

#: nova/exception.py:251
msgid "Invalid volume type"
msgstr ""

#: nova/exception.py:255
msgid "Invalid volume"
msgstr ""

#: nova/exception.py:259
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr ""

#: nova/exception.py:263
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr ""

#: nova/exception.py:267
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: nova/exception.py:271
#, python-format
msgid "Invalid cidr %(cidr)s."
msgstr ""

#: nova/exception.py:275
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: nova/exception.py:281
#, python-format
msgid "%(err)s"
msgstr ""

#: nova/exception.py:285
#, python-format
msgid ""
"Cannot perform action '%(action)s' on aggregate %(aggregate_id)s. Reason:"
" %(reason)s."
msgstr ""

#: nova/exception.py:290
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:294
#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."
msgstr ""

#: nova/exception.py:299
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr ""

#: nova/exception.py:303
#, python-format
msgid "Instance %(instance_id)s is not suspended."
msgstr ""

#: nova/exception.py:307
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr ""

#: nova/exception.py:311
msgid "Failed to suspend instance"
msgstr ""

#: nova/exception.py:315
msgid "Failed to resume server"
msgstr ""

#: nova/exception.py:319
msgid "Failed to reboot instance"
msgstr ""

#: nova/exception.py:323
msgid "Service is unavailable at this time."
msgstr ""

#: nova/exception.py:327
msgid "Volume service is unavailable at this time."
msgstr ""

#: nova/exception.py:331
msgid "Compute service is unavailable at this time."
msgstr ""

#: nova/exception.py:335
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""

#: nova/exception.py:340
msgid "Destination compute host is unavailable at this time."
msgstr ""

#: nova/exception.py:344
msgid "Original compute host is unavailable at this time."
msgstr ""

#: nova/exception.py:348
msgid "The supplied hypervisor type of is invalid."
msgstr ""

#: nova/exception.py:352
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr ""

#: nova/exception.py:357
#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""

#: nova/exception.py:362
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr ""

#: nova/exception.py:366
msgid "Unacceptable CPU info"
msgstr ""

#: nova/exception.py:370
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr ""

#: nova/exception.py:374
#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""

#: nova/exception.py:380
#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."
msgstr ""

#: nova/exception.py:387
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr ""

#: nova/exception.py:391
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:395
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:399
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr ""

#: nova/exception.py:403
msgid "Resource could not be found."
msgstr ""

#: nova/exception.py:408
#, python-format
msgid "Required flag %(flag)s not set."
msgstr ""

#: nova/exception.py:412
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: nova/exception.py:416
#, python-format
msgid "Unable to locate account %(account_name) on Solidfire device"
msgstr ""

#: nova/exception.py:420
#, python-format
msgid "Volume not found for instance %(instance_id)s."
msgstr ""

#: nova/exception.py:424
#, python-format
msgid "Volume %(volume_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:429
msgid "Zero volume types found."
msgstr ""

#: nova/exception.py:433
#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr ""

#: nova/exception.py:437
#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr ""

#: nova/exception.py:442
#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: nova/exception.py:447
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: nova/exception.py:451
#, python-format
msgid "deleting volume %(volume_name)s that has snapshot"
msgstr ""

#: nova/exception.py:455
#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent volumes"
msgstr ""

#: nova/exception.py:460
#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr ""

#: nova/exception.py:464
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: nova/exception.py:468
#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr ""

#: nova/exception.py:472
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: nova/exception.py:476
msgid ""
"Some images have been stored via hrefs. This version of the api does not "
"support displaying image hrefs."
msgstr ""

#: nova/exception.py:481
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: nova/exception.py:485
#, python-format
msgid "Kernel not found for image %(image_id)s."
msgstr ""

#: nova/exception.py:489
#, python-format
msgid "User %(user_id)s could not be found."
msgstr ""

#: nova/exception.py:493
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:497
#, python-format
msgid "User %(user_id)s is not a member of project %(project_id)s."
msgstr ""

#: nova/exception.py:501
#, python-format
msgid "Role %(role_id)s could not be found."
msgstr ""

#: nova/exception.py:505
msgid "Cannot find SR to read/write VDI."
msgstr ""

#: nova/exception.py:509
#, python-format
msgid "%(req)s is required to create a network."
msgstr ""

#: nova/exception.py:513
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr ""

#: nova/exception.py:517
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr ""

#: nova/exception.py:521
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr ""

#: nova/exception.py:525
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr ""

#: nova/exception.py:529
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr ""

#: nova/exception.py:533
msgid "No networks defined."
msgstr ""

#: nova/exception.py:537
#, python-format
msgid ""
"Either Network uuid %(network_uuid)s is not present or is not assigned to"
" the project %(project_id)s."
msgstr ""

#: nova/exception.py:542
#, python-format
msgid "Host is not set to the network (%(network_id)s)."
msgstr ""

#: nova/exception.py:546
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr ""

#: nova/exception.py:550
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr ""

#: nova/exception.py:554
#, python-format
msgid "Fixed ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:558
#, python-format
msgid "Instance %(instance_id)s has zero fixed ips."
msgstr ""

#: nova/exception.py:562
#, python-format
msgid "Network host %(host)s has zero fixed ips in network %(network_id)s."
msgstr ""

#: nova/exception.py:567
#, python-format
msgid "Instance %(instance_id)s doesn't have fixed ip '%(ip)s'."
msgstr ""

#: nova/exception.py:571
#, python-format
msgid "Host %(host)s has zero fixed ips."
msgstr ""

#: nova/exception.py:575
#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."
msgstr ""

#: nova/exception.py:580
#, python-format
msgid "Fixed IP address %(address)s is already in use."
msgstr ""

#: nova/exception.py:584
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr ""

#: nova/exception.py:588
msgid "Zero fixed ips available."
msgstr ""

#: nova/exception.py:592
msgid "Zero fixed ips could be found."
msgstr ""

#: nova/exception.py:596
#, python-format
msgid "Floating ip not found for id %(id)s."
msgstr ""

#: nova/exception.py:600
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr ""

#: nova/exception.py:604
#, python-format
msgid "Floating ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:608
#, python-format
msgid "Floating ip not found for host %(host)s."
msgstr ""

#: nova/exception.py:612
msgid "Zero floating ips available."
msgstr ""

#: nova/exception.py:616
#, python-format
msgid "Floating ip %(address)s is associated."
msgstr ""

#: nova/exception.py:620
#, python-format
msgid "Floating ip %(address)s is not associated."
msgstr ""

#: nova/exception.py:624
msgid "Zero floating ips exist."
msgstr ""

#: nova/exception.py:628
#, python-format
msgid "Interface %(interface)s not found."
msgstr ""

#: nova/exception.py:632
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr ""

#: nova/exception.py:636
#, python-format
msgid "Certificate %(certificate_id)s not found."
msgstr ""

#: nova/exception.py:640
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: nova/exception.py:644
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: nova/exception.py:648
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr ""

#: nova/exception.py:652
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: nova/exception.py:656
#, python-format
msgid "Auth token %(token)s could not be found."
msgstr ""

#: nova/exception.py:660
#, python-format
msgid "Access Key %(access_key)s could not be found."
msgstr ""

#: nova/exception.py:664
msgid "Quota could not be found"
msgstr ""

#: nova/exception.py:668
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:672
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr ""

#: nova/exception.py:676
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""

#: nova/exception.py:681
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr ""

#: nova/exception.py:685
#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"
msgstr ""

#: nova/exception.py:690
#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""

#: nova/exception.py:695
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: nova/exception.py:699
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: nova/exception.py:704
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr ""

#: nova/exception.py:708
#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."
msgstr ""

#: nova/exception.py:714
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr ""

#: nova/exception.py:718
#, python-format
msgid "Console for instance %(instance_id)s could not be found."
msgstr ""

#: nova/exception.py:722
#, python-format
msgid ""
"Console for instance %(instance_id)s in pool %(pool_id)s could not be "
"found."
msgstr ""

#: nova/exception.py:727
#, python-format
msgid "Invalid console type %(console_type)s "
msgstr ""

#: nova/exception.py:731
msgid "Zero instance types found."
msgstr ""

#: nova/exception.py:735
#, python-format
msgid "Instance type %(instance_type_id)s could not be found."
msgstr ""

#: nova/exception.py:739
#, python-format
msgid "Instance type with name %(instance_type_name)s could not be found."
msgstr ""

#: nova/exception.py:744
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr ""

#: nova/exception.py:748
#, python-format
msgid "Zone %(zone_id)s could not be found."
msgstr ""

#: nova/exception.py:752
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: nova/exception.py:756
#, python-format
msgid "Scheduler cost function %(cost_fn_str)s could not be found."
msgstr ""

#: nova/exception.py:761
#, python-format
msgid "Scheduler weight flag not found: %(flag_name)s"
msgstr ""

#: nova/exception.py:765
#, python-format
msgid "Instance %(instance_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:770
#, python-format
msgid ""
"Instance Type %(instance_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: nova/exception.py:775
msgid "LDAP object could not be found"
msgstr ""

#: nova/exception.py:779
#, python-format
msgid "LDAP user %(user_id)s could not be found."
msgstr ""

#: nova/exception.py:783
#, python-format
msgid "LDAP group %(group_id)s could not be found."
msgstr ""

#: nova/exception.py:787
#, python-format
msgid "LDAP user %(user_id)s is not a member of group %(group_id)s."
msgstr ""

#: nova/exception.py:791
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: nova/exception.py:795
msgid "Zero files could be found."
msgstr ""

#: nova/exception.py:799
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""

#: nova/exception.py:804
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr ""

#: nova/exception.py:808
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: nova/exception.py:812
msgid "Action not allowed."
msgstr ""

#: nova/exception.py:816
#, python-format
msgid "Unable to use global role %(role_id)s"
msgstr ""

#: nova/exception.py:820
msgid "Rotation is not allowed for snapshots"
msgstr ""

#: nova/exception.py:824
msgid "Rotation param is required for backup image_type"
msgstr ""

#: nova/exception.py:833
#, python-format
msgid "Key pair %(key_name)s already exists."
msgstr ""

#: nova/exception.py:837
#, python-format
msgid "User %(user)s already exists."
msgstr ""

#: nova/exception.py:841
#, python-format
msgid "LDAP user %(user)s already exists."
msgstr ""

#: nova/exception.py:845
#, python-format
msgid "LDAP group %(group)s already exists."
msgstr ""

#: nova/exception.py:849
#, python-format
msgid "User %(uid)s is already a member of the group %(group_dn)s"
msgstr "User %(uid)s is already a member of the group %(group_dn)s"

#: nova/exception.py:854
#, python-format
msgid "Project %(project)s already exists."
msgstr ""

#: nova/exception.py:858
#, python-format
msgid "Instance %(name)s already exists."
msgstr ""

#: nova/exception.py:862
#, python-format
msgid "Instance Type %(name)s already exists."
msgstr ""

#: nova/exception.py:866
#, python-format
msgid "Volume Type %(name)s already exists."
msgstr ""

#: nova/exception.py:870
#, python-format
msgid "%(path)s is on shared storage: %(reason)s"
msgstr ""

#: nova/exception.py:874
msgid "Migration error"
msgstr ""

#: nova/exception.py:878
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: nova/exception.py:882
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: nova/exception.py:886
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: nova/exception.py:890
msgid "Nova access parameters were not specified."
msgstr ""

#: nova/exception.py:894
#, python-format
msgid "Virtual Storage Array %(id)d could not be found."
msgstr ""

#: nova/exception.py:898
#, python-format
msgid "Virtual Storage Array %(name)s could not be found."
msgstr ""

#: nova/exception.py:902
msgid "When resizing, instances must change size!"
msgstr ""

#: nova/exception.py:906
msgid "Image is larger than instance type allows"
msgstr ""

#: nova/exception.py:910
msgid "1 or more Zones could not complete the request"
msgstr ""

#: nova/exception.py:914
msgid "Instance type's memory is too small for requested image."
msgstr ""

#: nova/exception.py:918
msgid "Instance type's disk is too small for requested image."
msgstr ""

#: nova/exception.py:922
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""

#: nova/exception.py:926
msgid "Could not fetch bandwidth/cpu/disk metrics for this host."
msgstr ""

#: nova/exception.py:930
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: nova/exception.py:934
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: nova/exception.py:938
msgid "Quota exceeded"
msgstr ""

#: nova/exception.py:942
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."
msgstr ""

#: nova/exception.py:947
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr ""

#: nova/exception.py:951
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr ""

#: nova/exception.py:955
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr ""

#: nova/exception.py:959
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:964
#, python-format
msgid "Host %(host)s already member of another aggregate."
msgstr ""

#: nova/exception.py:968
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr ""

#: nova/exception.py:972
msgid "Detected more than one volume with name %(vol_name)"
msgstr ""

#: nova/exception.py:976
#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s"
msgstr ""

#: nova/exception.py:981
msgid "Unable to create instance type"
msgstr ""

#: nova/exception.py:985
msgid "Bad response from SolidFire API"
msgstr ""

#: nova/exception.py:989
#, python-format
msgid "Error in SolidFire API response: status=%(status)s"
msgstr ""

#: nova/exception.py:993
#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr ""

#: nova/exception.py:997
msgid "Detected existing vlan with id %(vlan)"
msgstr ""

#: nova/exception.py:1001
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: nova/exception.py:1005
msgid "Invalid id: %(val) (expecting \"i-...\")."
msgstr ""

#: nova/log.py:310
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: nova/manager.py:146
#, python-format
msgid "Skipping %(full_task_name)s, %(ticks_to_skip)s ticks left until next run"
msgstr ""

#: nova/manager.py:152
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: nova/manager.py:159
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: nova/manager.py:203
msgid "Notifying Schedulers of capabilities ..."
msgstr ""

#: nova/policy.py:30
msgid "JSON file representing policy"
msgstr ""

#: nova/policy.py:33
msgid "Rule checked when requested rule is not found"
msgstr ""

#: nova/service.py:159
#, python-format
msgid "Starting %(topic)s node (version %(vcs_string)s)"
msgstr "Starting %(topic)s node (version %(vcs_string)s)"

#: nova/service.py:177
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: nova/service.py:251
msgid "Service killed that has no database entry"
msgstr "Service killed that has no database entry"

#: nova/service.py:288
msgid "The service database object disappeared, Recreating it."
msgstr "The service database object disappeared, Recreating it."

#: nova/service.py:303
msgid "Recovered model server connection!"
msgstr "Recovered model server connection!"

#: nova/service.py:309
msgid "model server went away"
msgstr "model server went away"

#: nova/service.py:402
msgid "Full set of FLAGS:"
msgstr ""

#: nova/service.py:409
#, python-format
msgid "%(flag)s : FLAG SET "
msgstr ""

#: nova/utils.py:74
#, python-format
msgid "Inner Exception: %s"
msgstr "Inner Exception: %s"

#: nova/utils.py:158
#, python-format
msgid "Fetching %s"
msgstr "Fetching %s"

#: nova/utils.py:199
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: nova/utils.py:209
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "Running cmd (subprocess): %s"

#: nova/utils.py:225 nova/utils.py:304
#, python-format
msgid "Result was %s"
msgstr "Result was %s"

#: nova/utils.py:238
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: nova/utils.py:280
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "Running cmd (SSH): %s"

#: nova/utils.py:282
msgid "Environment not supported over SSH"
msgstr ""

#: nova/utils.py:286
msgid "process_input not supported over SSH"
msgstr ""

#: nova/utils.py:345
#, python-format
msgid "debug in callback: %s"
msgstr "debug in callback: %s"

#: nova/utils.py:478
#, python-format
msgid "Link Local address is not found.:%s"
msgstr "Link Local address is not found.:%s"

#: nova/utils.py:481
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr "Couldn't get Link Local IP of %(interface)s :%(ex)s"

#: nova/utils.py:592
#, python-format
msgid "Invalid backend: %s"
msgstr "Invalid backend: %s"

#: nova/utils.py:603
#, python-format
msgid "backend %s"
msgstr "backend %s"

#: nova/utils.py:652
msgid "in looping call"
msgstr ""

#: nova/utils.py:828
#, python-format
msgid "Attempting to grab semaphore \"%(lock)s\" for method \"%(method)s\"...lock"
msgstr ""

#: nova/utils.py:832
#, python-format
msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"...lock"
msgstr ""

#: nova/utils.py:836
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\" for method \"%(method)s\"...lock"
msgstr ""

#: nova/utils.py:843
#, python-format
msgid "Got file lock \"%(lock)s\" for method \"%(method)s\"...lock"
msgstr ""

#: nova/utils.py:902
#, python-format
msgid "Found sentinel %(filename)s for pid %(pid)sfilename"
msgstr ""

#: nova/utils.py:906
#, python-format
msgid "Cleaned sentinel %(filename)s for pid %(pid)sfilename"
msgstr ""

#: nova/utils.py:921
#, python-format
msgid "Found lockfile %(file)s with link count %(count)dfile"
msgstr ""

#: nova/utils.py:926
#, python-format
msgid "Cleaned lockfile %(file)s with link count %(count)dfile"
msgstr ""

#: nova/utils.py:1036
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: nova/utils.py:1067
#, python-format
msgid "Invalid server_string: %s"
msgstr ""

#: nova/utils.py:1192
#, python-format
msgid "timefunc: '%(name)s' took %(total_time).2f secs"
msgstr ""

#: nova/utils.py:1224
msgid "Original exception being dropped"
msgstr ""

#: nova/utils.py:1343
#, python-format
msgid "Class %(fullname)s is deprecated: %(msg)s"
msgstr ""

#: nova/utils.py:1345
#, python-format
msgid "Class %(fullname)s is deprecated"
msgstr ""

#: nova/utils.py:1377
#, python-format
msgid "Function %(name)s in %(location)s is deprecated: %(msg)s"
msgstr ""

#: nova/utils.py:1379
#, python-format
msgid "Function %(name)s in %(location)s is deprecated"
msgstr ""

#: nova/wsgi.py:93
#, python-format
msgid "Started %(name)s on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:104
msgid "Stopping WSGI server."
msgstr ""

#: nova/wsgi.py:107
msgid "Stopping raw TCP server."
msgstr ""

#: nova/wsgi.py:113
#, python-format
msgid "Starting TCP server %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:129
msgid "WSGI server has stopped."
msgstr ""

#: nova/wsgi.py:207
msgid "You must implement __call__"
msgstr "You must implement __call__"

#: nova/api/direct.py:218
msgid "not available"
msgstr "not available"

#: nova/api/direct.py:299
#, python-format
msgid "Returned non-serializeable type: %s"
msgstr ""

#: nova/api/ec2/__init__.py:69
#, python-format
msgid "%(code)s: %(message)s"
msgstr ""

#: nova/api/ec2/__init__.py:91
#, python-format
msgid "FaultWrapper: %s"
msgstr ""

#: nova/api/ec2/__init__.py:166
msgid "Too many failed authentications."
msgstr "Too many failed authentications."

#: nova/api/ec2/__init__.py:176
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and"
" will be locked out for %(lock_mins)d minutes."
msgstr ""
"Access key %(access_key)s has had %(failures)d failed authentications and"
" will be locked out for %(lock_mins)d minutes."

#: nova/api/ec2/__init__.py:263
msgid "Signature not provided"
msgstr ""

#: nova/api/ec2/__init__.py:267
msgid "Access key not provided"
msgstr ""

#: nova/api/ec2/__init__.py:302 nova/api/ec2/__init__.py:315
msgid "Failure communicating with keystone"
msgstr ""

#: nova/api/ec2/__init__.py:385
#, python-format
msgid "Authentication Failure: %s"
msgstr "Authentication Failure: %s"

#: nova/api/ec2/__init__.py:401
#, python-format
msgid "Authenticated Request For %(uname)s:%(pname)s)"
msgstr "Authenticated Request For %(uname)s:%(pname)s)"

#: nova/api/ec2/__init__.py:432
#, python-format
msgid "action: %s"
msgstr "action: %s"

#: nova/api/ec2/__init__.py:434
#, python-format
msgid "arg: %(key)s\t\tval: %(value)s"
msgstr "arg: %(key)s\t\tval: %(value)s"

#: nova/api/ec2/__init__.py:509
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr "Unauthorised request for controller=%(controller)s and action=%(action)s"

#: nova/api/ec2/__init__.py:581
#, python-format
msgid "InstanceNotFound raised: %s"
msgstr "InstanceNotFound raised: %s"

#: nova/api/ec2/__init__.py:587
#, python-format
msgid "VolumeNotFound raised: %s"
msgstr "VolumeNotFound raised: %s"

#: nova/api/ec2/__init__.py:593
#, python-format
msgid "SnapshotNotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:599
#, python-format
msgid "NotFound raised: %s"
msgstr "NotFound raised: %s"

#: nova/api/ec2/__init__.py:602
#, python-format
msgid "EC2APIError raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:610
#, python-format
msgid "KeyPairExists raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:614
#, python-format
msgid "InvalidParameterValue raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:618
#, python-format
msgid "InvalidPortRange raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:622
#, python-format
msgid "NotAuthorized raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:626
#, python-format
msgid "InvalidRequest raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:630
#, fuzzy, python-format
msgid "ValidatorError raised: %s"
msgstr "Unexpected error raised: %s"

#: nova/api/ec2/__init__.py:641
#, python-format
msgid "Unexpected error raised: %s"
msgstr "Unexpected error raised: %s"

#: nova/api/ec2/__init__.py:642
#, python-format
msgid "Environment: %s"
msgstr ""

#: nova/api/ec2/__init__.py:644 nova/api/metadata/handler.py:250
msgid "An unknown error has occurred. Please try your request again."
msgstr "An unknown error has occurred. Please try your request again."

#: nova/api/ec2/apirequest.py:64
#, python-format
msgid "Unsupported API request: controller = %(controller)s, action = %(action)s"
msgstr "Unsupported API request: controller = %(controller)s, action = %(action)s"

#: nova/api/ec2/cloud.py:337
#, python-format
msgid "Create snapshot of volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:372
#, python-format
msgid "Create key pair %s"
msgstr "Create key pair %s"

#: nova/api/ec2/cloud.py:381
#, python-format
msgid "Import key %s"
msgstr ""

#: nova/api/ec2/cloud.py:399
#, python-format
msgid "Delete key pair %s"
msgstr "Delete key pair %s"

#: nova/api/ec2/cloud.py:659 nova/api/ec2/cloud.py:719
msgid "No rule for the specified parameters."
msgstr "No rule for the specified parameters."

#: nova/api/ec2/cloud.py:744
#, python-format
msgid ""
"Value (%s) for parameter GroupName is invalid. Content limited to "
"Alphanumeric characters, spaces, dashes, and underscores."
msgstr ""

#: nova/api/ec2/cloud.py:751
#, python-format
msgid ""
"Value (%s) for parameter GroupName is invalid. Length exceeds maximum of "
"255."
msgstr ""

#: nova/api/ec2/cloud.py:755
#: nova/api/openstack/compute/contrib/security_groups.py:292
#, python-format
msgid "Create Security Group %s"
msgstr "Create Security Group %s"

#: nova/api/ec2/cloud.py:758
#, python-format
msgid "group %s already exists"
msgstr "group %s already exists"

#: nova/api/ec2/cloud.py:790
#: nova/api/openstack/compute/contrib/security_groups.py:245
#, python-format
msgid "Delete security group %s"
msgstr "Delete security group %s"

#: nova/api/ec2/cloud.py:798 nova/compute/manager.py:1589
#, python-format
msgid "Get console output for instance %s"
msgstr "Get console output for instance %s"

#: nova/api/ec2/cloud.py:869
#, python-format
msgid "Create volume from snapshot %s"
msgstr ""

#: nova/api/ec2/cloud.py:873 nova/api/openstack/compute/contrib/volumes.py:186
#: nova/api/openstack/volume/volumes.py:215
#, python-format
msgid "Create volume of %s GB"
msgstr "Create volume of %s GB"

#: nova/api/ec2/cloud.py:901
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"

#: nova/api/ec2/cloud.py:916 nova/api/openstack/compute/contrib/volumes.py:366
#, python-format
msgid "Detach volume %s"
msgstr "Detach volume %s"

#: nova/api/ec2/cloud.py:943 nova/api/ec2/cloud.py:1000
#: nova/api/ec2/cloud.py:1467 nova/api/ec2/cloud.py:1482
#, python-format
msgid "attribute not supported: %s"
msgstr "attribute not supported: %s"

#: nova/api/ec2/cloud.py:1066
#, python-format
msgid "vol = %s\n"
msgstr ""

#: nova/api/ec2/cloud.py:1211
msgid "Allocate address"
msgstr "Allocate address"

#: nova/api/ec2/cloud.py:1223
#, python-format
msgid "Release address %s"
msgstr "Release address %s"

#: nova/api/ec2/cloud.py:1228
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr "Associate address %(public_ip)s to instance %(instance_id)s"

#: nova/api/ec2/cloud.py:1238
#, python-format
msgid "Disassociate address %s"
msgstr "Disassociate address %s"

#: nova/api/ec2/cloud.py:1263
msgid "Image must be available"
msgstr ""

#: nova/api/ec2/cloud.py:1284
msgid "Going to start terminating instances"
msgstr "Going to start terminating instances"

#: nova/api/ec2/cloud.py:1298
#, python-format
msgid "Reboot instance %r"
msgstr "Reboot instance %r"

#: nova/api/ec2/cloud.py:1309
msgid "Going to stop instances"
msgstr ""

#: nova/api/ec2/cloud.py:1320
msgid "Going to start instances"
msgstr ""

#: nova/api/ec2/cloud.py:1412
#, python-format
msgid "De-registering image %s"
msgstr "De-registering image %s"

#: nova/api/ec2/cloud.py:1439
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr "Registered image %(image_location)s with id %(image_id)s"

#: nova/api/ec2/cloud.py:1485
msgid "user or group not specified"
msgstr "user or group not specified"

#: nova/api/ec2/cloud.py:1487
msgid "only group \"all\" is supported"
msgstr "only group \"all\" is supported"

#: nova/api/ec2/cloud.py:1489
msgid "operation_type must be add or remove"
msgstr "operation_type must be add or remove"

#: nova/api/ec2/cloud.py:1491
#, python-format
msgid "Updating image %s publicity"
msgstr "Updating image %s publicity"

#: nova/api/ec2/cloud.py:1548
#, python-format
msgid "Couldn't stop instance with in %d sec"
msgstr ""

#: nova/api/metadata/handler.py:248 nova/api/metadata/handler.py:255
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr "Failed to get metadata for ip: %s"

#: nova/api/openstack/__init__.py:43
#, python-format
msgid "Caught error: %s"
msgstr "Caught error: %s"

#: nova/api/openstack/__init__.py:45 nova/api/openstack/wsgi.py:881
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: nova/api/openstack/__init__.py:94
msgid "Must specify an ExtensionManager class"
msgstr ""

#: nova/api/openstack/__init__.py:105
#, python-format
msgid "Extended resource: %s"
msgstr ""

#: nova/api/openstack/__init__.py:130
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: nova/api/openstack/__init__.py:135
#, python-format
msgid "Extension %(ext_name)s extending resource: %(collection)s"
msgstr ""

#: nova/api/openstack/auth.py:91
#, python-format
msgid "%(user_id)s could not be found with token '%(token)s'"
msgstr ""

#: nova/api/openstack/auth.py:135
#, python-format
msgid "%(user_id)s must be an admin or a member of %(project_id)s"
msgstr ""

#: nova/api/openstack/auth.py:153
msgid "Authentication requests must be made against a version root (e.g. /v2)."
msgstr ""

#: nova/api/openstack/auth.py:168
#, python-format
msgid "Could not find %s in request."
msgstr ""

#: nova/api/openstack/auth.py:192
#, python-format
msgid "Successfully authenticated '%s'"
msgstr ""

#: nova/api/openstack/auth.py:242
msgid "User not found with provided API key."
msgstr ""

#: nova/api/openstack/auth.py:259
#, python-format
msgid "Provided API key is valid, but not for user '%(username)s'"
msgstr ""

#: nova/api/openstack/common.py:135 nova/api/openstack/common.py:170
msgid "limit param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:138 nova/api/openstack/common.py:174
msgid "limit param must be positive"
msgstr ""

#: nova/api/openstack/common.py:164
msgid "offset param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:178
msgid "offset param must be positive"
msgstr ""

#: nova/api/openstack/common.py:202
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: nova/api/openstack/common.py:242
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: nova/api/openstack/common.py:277
msgid "Image metadata limit exceeded"
msgstr ""

#: nova/api/openstack/common.py:334
#, python-format
msgid "Cannot '%(action)s' while instance is in %(attr)s %(state)s"
msgstr ""

#: nova/api/openstack/common.py:337
#, python-format
msgid "Instance is in an invalid state for '%(action)s'"
msgstr ""

#: nova/api/openstack/common.py:417
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: nova/api/openstack/common.py:419
msgid "Instance snapshots are not permitted at this time."
msgstr ""

#: nova/api/openstack/extensions.py:191
#, python-format
msgid "Loaded extension: %s"
msgstr ""

#: nova/api/openstack/extensions.py:228
#, python-format
msgid "Ext name: %s"
msgstr ""

#: nova/api/openstack/extensions.py:229
#, python-format
msgid "Ext alias: %s"
msgstr ""

#: nova/api/openstack/extensions.py:230
#, python-format
msgid "Ext description: %s"
msgstr ""

#: nova/api/openstack/extensions.py:232
#, python-format
msgid "Ext namespace: %s"
msgstr ""

#: nova/api/openstack/extensions.py:233
#, python-format
msgid "Ext updated: %s"
msgstr ""

#: nova/api/openstack/extensions.py:235
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: nova/api/openstack/extensions.py:249
#, python-format
msgid "Loading extension %s"
msgstr ""

#: nova/api/openstack/extensions.py:255
#, python-format
msgid "Calling extension factory %s"
msgstr ""

#: nova/api/openstack/extensions.py:267
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:345
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:369
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: nova/api/openstack/wsgi.py:134 nova/api/openstack/wsgi.py:537
msgid "cannot understand JSON"
msgstr ""

#: nova/api/openstack/wsgi.py:158
#: nova/api/openstack/compute/contrib/hosts.py:86
msgid "cannot understand XML"
msgstr ""

#: nova/api/openstack/wsgi.py:542
msgid "too many body keys"
msgstr ""

#: nova/api/openstack/wsgi.py:580
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:583
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:691
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:695
msgid "No Content-Type provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:699
msgid "Empty body provided in request"
msgstr ""

#: nova/api/openstack/wsgi.py:810
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:813 nova/api/openstack/wsgi.py:826
#: nova/api/openstack/compute/server_metadata.py:58
#: nova/api/openstack/compute/server_metadata.py:76
#: nova/api/openstack/compute/server_metadata.py:103
#: nova/api/openstack/compute/server_metadata.py:128
#: nova/api/openstack/compute/contrib/admin_actions.py:211
#: nova/api/openstack/compute/contrib/console_output.py:51
msgid "Malformed request body"
msgstr ""

#: nova/api/openstack/wsgi.py:823
msgid "Unsupported Content-Type"
msgstr ""

#: nova/api/openstack/wsgi.py:835
msgid "Malformed request url"
msgstr ""

#: nova/api/openstack/wsgi.py:884
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: nova/api/openstack/xmlutil.py:265
msgid "element is not a child"
msgstr ""

#: nova/api/openstack/xmlutil.py:414
msgid "root element selecting a list"
msgstr ""

#: nova/api/openstack/xmlutil.py:739
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: nova/api/openstack/xmlutil.py:858
msgid "subclasses must implement construct()!"
msgstr ""

#: nova/api/openstack/compute/extensions.py:29
#: nova/api/openstack/volume/extensions.py:29
msgid "Initializing extension manager."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:40
#: nova/api/openstack/compute/images.py:142
#: nova/api/openstack/compute/images.py:157
msgid "Image not found."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:79
msgid "Incorrect request body format"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:83
#: nova/api/openstack/compute/server_metadata.py:82
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:79
#: nova/api/openstack/compute/contrib/volumetypes.py:188
msgid "Request body and URI mismatch"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:86
#: nova/api/openstack/compute/server_metadata.py:86
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:82
#: nova/api/openstack/compute/contrib/volumetypes.py:191
msgid "Request body contains too many items"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:111
msgid "Invalid metadata key"
msgstr ""

#: nova/api/openstack/compute/ips.py:74
msgid "Instance does not exist"
msgstr ""

#: nova/api/openstack/compute/ips.py:97
msgid "Instance is not a member of specified network"
msgstr ""

#: nova/api/openstack/compute/limits.py:140
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: nova/api/openstack/compute/limits.py:266
msgid "This request was rate-limited."
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:38
#: nova/api/openstack/compute/server_metadata.py:124
#: nova/api/openstack/compute/server_metadata.py:163
msgid "Server does not exist"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:143
#: nova/api/openstack/compute/server_metadata.py:156
msgid "Metadata item was not found"
msgstr ""

#: nova/api/openstack/compute/servers.py:425
#, python-format
msgid "Invalid server status: %(status)s"
msgstr ""

#: nova/api/openstack/compute/servers.py:433
msgid "Invalid changes-since value"
msgstr ""

#: nova/api/openstack/compute/servers.py:483
msgid "Personality file limit exceeded"
msgstr ""

#: nova/api/openstack/compute/servers.py:485
msgid "Personality file path too long"
msgstr ""

#: nova/api/openstack/compute/servers.py:487
msgid "Personality file content too long"
msgstr ""

#: nova/api/openstack/compute/servers.py:500
msgid "Server name is not a string or unicode"
msgstr ""

#: nova/api/openstack/compute/servers.py:504
msgid "Server name is an empty string"
msgstr ""

#: nova/api/openstack/compute/servers.py:522
#, python-format
msgid "Bad personality format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:525
msgid "Bad personality format"
msgstr ""

#: nova/api/openstack/compute/servers.py:530
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:545
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:554
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:561
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr ""

#: nova/api/openstack/compute/servers.py:567
#, python-format
msgid "Bad network format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:570
msgid "Bad networks format"
msgstr ""

#: nova/api/openstack/compute/servers.py:582
msgid "Userdata content cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:589
#: nova/api/openstack/compute/servers.py:596
msgid "accessIPv4 is not proper IPv4 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:628
msgid "Server name is not defined"
msgstr ""

#: nova/api/openstack/compute/servers.py:642
msgid "Invalid imageRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:677
#: nova/api/openstack/compute/servers.py:742
msgid "Invalid flavorRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:739
msgid "Can not find requested image"
msgstr ""

#: nova/api/openstack/compute/servers.py:745
msgid "Invalid key_name provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:832
#: nova/api/openstack/compute/servers.py:852
msgid "Instance has not been resized."
msgstr ""

#: nova/api/openstack/compute/servers.py:838
#, python-format
msgid "Error in confirm-resize %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:858
#, python-format
msgid "Error in revert-resize %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:871
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr ""

#: nova/api/openstack/compute/servers.py:875
msgid "Missing argument 'type' for reboot"
msgstr ""

#: nova/api/openstack/compute/servers.py:888
#, python-format
msgid "Error in reboot %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:900
msgid "Unable to locate requested flavor."
msgstr ""

#: nova/api/openstack/compute/servers.py:903
msgid "Resize requires a change in size."
msgstr ""

#: nova/api/openstack/compute/servers.py:927
msgid "Malformed server entity"
msgstr ""

#: nova/api/openstack/compute/servers.py:934
msgid "Missing imageRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:941
msgid "Missing flavorRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:954
msgid "No adminPass was specified"
msgstr ""

#: nova/api/openstack/compute/servers.py:958
#: nova/api/openstack/compute/servers.py:1134
msgid "Invalid adminPass"
msgstr ""

#: nova/api/openstack/compute/servers.py:972
msgid "Unable to parse metadata key/value pairs."
msgstr ""

#: nova/api/openstack/compute/servers.py:985
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:988
msgid "Resize requests require 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1006
#: nova/api/openstack/compute/contrib/aggregates.py:142
#: nova/api/openstack/compute/contrib/networks.py:65
msgid "Invalid request body"
msgstr ""

#: nova/api/openstack/compute/servers.py:1011
msgid "Could not parse imageRef from request."
msgstr ""

#: nova/api/openstack/compute/servers.py:1061
msgid "Instance could not be found"
msgstr ""

#: nova/api/openstack/compute/servers.py:1064
msgid "Cannot find image for rebuild"
msgstr ""

#: nova/api/openstack/compute/servers.py:1093
msgid "createImage entity requires name attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1102
#: nova/api/openstack/compute/contrib/admin_actions.py:238
msgid "Invalid metadata"
msgstr ""

#: nova/api/openstack/compute/servers.py:1157
#, python-format
msgid "Removing options '%(unk_opt_str)s' from query"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:60
#, python-format
msgid "Compute.api::pause %s"
msgstr "Compute.api::pause %s"

#: nova/api/openstack/compute/contrib/admin_actions.py:77
#, python-format
msgid "Compute.api::unpause %s"
msgstr "Compute.api::unpause %s"

#: nova/api/openstack/compute/contrib/admin_actions.py:94
#, python-format
msgid "compute.api::suspend %s"
msgstr "compute.api::suspend %s"

#: nova/api/openstack/compute/contrib/admin_actions.py:111
#, python-format
msgid "compute.api::resume %s"
msgstr "compute.api::resume %s"

#: nova/api/openstack/compute/contrib/admin_actions.py:127
#, python-format
msgid "Error in migrate %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:141
#, python-format
msgid "Compute.api::reset_network %s"
msgstr "Compute.api::reset_network %s"

#: nova/api/openstack/compute/contrib/admin_actions.py:154
#: nova/api/openstack/compute/contrib/admin_actions.py:170
#: nova/api/openstack/compute/contrib/admin_actions.py:186
#: nova/api/openstack/compute/contrib/multinic.py:41
#: nova/api/openstack/compute/contrib/rescue.py:43
msgid "Server not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:157
#, python-format
msgid "Compute.api::inject_network_info %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:173
#, python-format
msgid "Compute.api::lock %s"
msgstr "Compute.api::lock %s"

#: nova/api/openstack/compute/contrib/admin_actions.py:189
#, python-format
msgid "Compute.api::unlock %s"
msgstr "Compute.api::unlock %s"

#: nova/api/openstack/compute/contrib/admin_actions.py:219
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:223
msgid "Malformed createBackup entity"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:229
msgid "createBackup attribute 'rotation' must be an integer"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:244
#: nova/api/openstack/compute/contrib/console_output.py:46
#: nova/api/openstack/compute/contrib/console_output.py:58
#: nova/api/openstack/compute/contrib/consoles.py:49
#: nova/api/openstack/compute/contrib/consoles.py:60
#: nova/api/openstack/compute/contrib/server_action_list.py:49
#: nova/api/openstack/compute/contrib/server_diagnostics.py:47
#: nova/api/openstack/compute/contrib/server_start_stop.py:38
msgid "Instance not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:272
msgid "host and block_migration must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:284
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:76
#, python-format
msgid ""
"Cannot create aggregate with name %(name)s and availability zone "
"%(avail_zone)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:88
#, python-format
msgid "Cannot show aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:114
#, python-format
msgid "Cannot update aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:126
#, python-format
msgid "Cannot delete aggregate: %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:139
#, python-format
msgid "Aggregates does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:152
#: nova/api/openstack/compute/contrib/aggregates.py:158
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:171
#: nova/api/openstack/compute/contrib/aggregates.py:175
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:195
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/certificates.py:75
msgid "Only root certificate can be retrieved."
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe.py:117
msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:44
msgid "Missing type specification"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:56
msgid "Invalid type specification"
msgstr ""

#: nova/api/openstack/compute/contrib/disk_config.py:44
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr ""

#: nova/api/openstack/compute/contrib/extended_server_attributes.py:65
#: nova/api/openstack/compute/contrib/extended_status.py:61
msgid "Server not found."
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextradata.py:60
#: nova/api/openstack/compute/contrib/flavorextradata.py:90
msgid "Flavor not found."
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:49
#: nova/api/openstack/compute/contrib/volumetypes.py:158
msgid "No Request Body"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:159
#, python-format
msgid "No more floating ips in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:161
msgid "No more floating ips available."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:201
#: nova/api/openstack/compute/contrib/floating_ips.py:230
#: nova/api/openstack/compute/contrib/security_groups.py:560
#: nova/api/openstack/compute/contrib/security_groups.py:593
msgid "Missing parameter dict"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:204
#: nova/api/openstack/compute/contrib/floating_ips.py:233
msgid "Address not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:213
msgid "No fixed ips associated to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:216
msgid "Associate floating ip failed"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:144
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:148
#, fuzzy, python-format
msgid "Invalid mode: '%s'"
msgstr "Invalid backend: %s"

#: nova/api/openstack/compute/contrib/hosts.py:152
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:170
#, python-format
msgid "Putting host %(host)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:181
#, python-format
msgid "Setting host %(host)s to %(state)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:228
msgid "Describe-resource is admin only functionality"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:236
msgid "Host not found"
msgstr ""

#: nova/api/openstack/compute/contrib/keypairs.py:85
msgid "Keypair name must be between 1 and 255 characters long"
msgstr ""

#: nova/api/openstack/compute/contrib/keypairs.py:90
#, python-format
msgid "Key pair '%s' already exists."
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:52
msgid "Missing 'networkId' argument for addFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:68
msgid "Missing 'address' argument for removeFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:77
#, python-format
msgid "Unable to find address %r"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:62
#, python-format
msgid "Network does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:70
#, python-format
msgid "Disassociating network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:74
#: nova/api/openstack/compute/contrib/networks.py:91
#: nova/api/openstack/compute/contrib/networks.py:101
msgid "Network not found"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:87
#, python-format
msgid "Showing network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/networks.py:97
#, python-format
msgid "Deleting network with id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/scheduler_hints.py:41
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:222
msgid "Security group id should be integer"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:243
#, fuzzy, python-format
msgid "Security group is still in use"
msgstr "Revoke security group ingress %s"

#: nova/api/openstack/compute/contrib/security_groups.py:295
#, python-format
msgid "Security group %s already exists"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:315
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:318
#, python-format
msgid "Security group %s cannot be empty."
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:321
#, python-format
msgid "Security group %s should not be greater than 255 characters."
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:348
msgid "Parent group id is not integer"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:351
#, python-format
msgid "Security group (%s) not found"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:354
#, python-format
msgid "Authorize security group ingress %s"
msgstr "Authorise security group ingress %s"

#: nova/api/openstack/compute/contrib/security_groups.py:369
msgid "Not enough parameters to build a valid rule."
msgstr "Not enough parameters to build a valid rule."

#: nova/api/openstack/compute/contrib/security_groups.py:376
#, python-format
msgid "This rule already exists in group %s"
msgstr "This rule already exists in group %s"

#: nova/api/openstack/compute/contrib/security_groups.py:414
msgid "Parent or group id is not integer"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:418
msgid "Parent group id and group id cannot be same"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:496
msgid "Rule id is not integer"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:499
#, python-format
msgid "Rule (%s) not found"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:506
#, python-format
msgid "Revoke security group ingress %s"
msgstr "Revoke security group ingress %s"

#: nova/api/openstack/compute/contrib/security_groups.py:563
#: nova/api/openstack/compute/contrib/security_groups.py:596
msgid "Security group not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:567
#: nova/api/openstack/compute/contrib/security_groups.py:600
msgid "Security group name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:45
#, python-format
msgid "start instance %r"
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:54
#, python-format
msgid "stop instance %r"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:170
msgid "No body provided"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:182
#, python-format
msgid "Create VSA %(display_name)s of type %(vc_type)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:203
#, python-format
msgid "Delete VSA with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:222
#, python-format
msgid "Associate address %(ip)s to VSA %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:251
#, python-format
msgid "Disassociate address from VSA %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:291
#, python-format
msgid "%(obj)s with ID %(id)s not found"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:297
#, python-format
msgid ""
"%(obj)s with ID %(id)s belongs to VSA %(own_vsa_id)s and not to VSA "
"%(vsa_id)s."
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:317
#, python-format
msgid "Index. vsa_id=%(vsa_id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:322
#, python-format
msgid "Detail. vsa_id=%(vsa_id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:327
#, python-format
msgid "Create. vsa_id=%(vsa_id)s, body=%(body)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:336
#, python-format
msgid "Create volume of %(size)s GB from VSA ID %(vsa_id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:381
#, python-format
msgid "Update %(obj)s with id: %(id)s, changes: %(changes)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:396
#, python-format
msgid "Delete. vsa_id=%(vsa_id)s, id=%(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:412
#, python-format
msgid "Show. vsa_id=%(vsa_id)s, id=%(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/virtual_storage_arrays.py:623
#, python-format
msgid "Index instances for VSA %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:73
#: nova/api/openstack/volume/volumes.py:99
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:146
#: nova/api/openstack/volume/volumes.py:177
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:329
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:481
#: nova/api/openstack/volume/snapshots.py:109
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:523
#: nova/api/openstack/volume/snapshots.py:149
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/auth/fakeldap.py:33
msgid "Attempted to instantiate singleton"
msgstr "Attempted to instantiate singleton"

#: nova/auth/ldapdriver.py:650
#, python-format
msgid ""
"Attempted to remove the last member of a group. Deleting the group at %s "
"instead."
msgstr ""
"Attempted to remove the last member of a group. Deleting the group at %s "
"instead."

#: nova/auth/manager.py:297
#, python-format
msgid "Looking up user: %r"
msgstr "Looking up user: %r"

#: nova/auth/manager.py:301
#, python-format
msgid "Failed authorization for access key %s"
msgstr "Failed authorisation for access key %s"

#: nova/auth/manager.py:307
#, python-format
msgid "Using project name = user name (%s)"
msgstr "Using project name = user name (%s)"

#: nova/auth/manager.py:314
#, python-format
msgid "failed authorization: no project named %(pjid)s (user=%(uname)s)"
msgstr "failed authorisation: no project named %(pjid)s (user=%(uname)s)"

#: nova/auth/manager.py:323
#, python-format
msgid ""
"Failed authorization: user %(uname)s not admin and not member of project "
"%(pjname)s"
msgstr ""
"Failed authorisation: user %(uname)s not admin and not member of project "
"%(pjname)s"

#: nova/auth/manager.py:330 nova/auth/manager.py:342
#, python-format
msgid "user.secret: %s"
msgstr ""

#: nova/auth/manager.py:331 nova/auth/manager.py:343
#, python-format
msgid "expected_signature: %s"
msgstr ""

#: nova/auth/manager.py:332 nova/auth/manager.py:344
#, python-format
msgid "signature: %s"
msgstr ""

#: nova/auth/manager.py:334 nova/auth/manager.py:356
#, python-format
msgid "Invalid signature for user %s"
msgstr "Invalid signature for user %s"

#: nova/auth/manager.py:352
#, python-format
msgid "host_only_signature: %s"
msgstr ""

#: nova/auth/manager.py:448
msgid "Must specify project"
msgstr "Must specify project"

#: nova/auth/manager.py:489
#, python-format
msgid "Adding role %(role)s to user %(uid)s in project %(pid)s"
msgstr "Adding role %(role)s to user %(uid)s in project %(pid)s"

#: nova/auth/manager.py:492
#, python-format
msgid "Adding sitewide role %(role)s to user %(uid)s"
msgstr "Adding sitewide role %(role)s to user %(uid)s"

#: nova/auth/manager.py:518
#, python-format
msgid "Removing role %(role)s from user %(uid)s on project %(pid)s"
msgstr "Removing role %(role)s from user %(uid)s on project %(pid)s"

#: nova/auth/manager.py:521
#, python-format
msgid "Removing sitewide role %(role)s from user %(uid)s"
msgstr "Removing sitewide role %(role)s from user %(uid)s"

#: nova/auth/manager.py:594
#, python-format
msgid "Created project %(name)s with manager %(manager_user)s"
msgstr "Created project %(name)s with manager %(manager_user)s"

#: nova/auth/manager.py:612
#, python-format
msgid "modifying project %s"
msgstr "modifying project %s"

#: nova/auth/manager.py:624
#, python-format
msgid "Adding user %(uid)s to project %(pid)s"
msgstr "Adding user %(uid)s to project %(pid)s"

#: nova/auth/manager.py:645
#, python-format
msgid "Remove user %(uid)s from project %(pid)s"
msgstr "Remove user %(uid)s from project %(pid)s"

#: nova/auth/manager.py:675
#, python-format
msgid "Deleting project %s"
msgstr "Deleting project %s"

#: nova/auth/manager.py:733
#, python-format
msgid "Created user %(rvname)s (admin: %(rvadmin)r)"
msgstr "Created user %(rvname)s (admin: %(rvadmin)r)"

#: nova/auth/manager.py:742
#, python-format
msgid "Deleting user %s"
msgstr "Deleting user %s"

#: nova/auth/manager.py:752
#, python-format
msgid "Access Key change for user %s"
msgstr "Access Key change for user %s"

#: nova/auth/manager.py:754
#, python-format
msgid "Secret Key change for user %s"
msgstr "Secret Key change for user %s"

#: nova/auth/manager.py:756
#, python-format
msgid "Admin status set to %(admin)r for user %(uid)s"
msgstr "Admin status set to %(admin)r for user %(uid)s"

#: nova/auth/manager.py:801
#, python-format
msgid "No vpn data for project %s"
msgstr "No vpn data for project %s"

#: nova/cloudpipe/pipelib.py:46
msgid "Template for cloudpipe instance boot script"
msgstr ""

#: nova/cloudpipe/pipelib.py:49
msgid "Network to push into openvpn config"
msgstr "Network to push into openvpn config"

#: nova/cloudpipe/pipelib.py:52
msgid "Netmask to push into openvpn config"
msgstr "Netmask to push into openvpn config"

#: nova/cloudpipe/pipelib.py:101
#, python-format
msgid "Launching VPN for %s"
msgstr "Launching VPN for %s"

#: nova/compute/api.py:149
#, python-format
msgid ""
"Quota exceeded for %(pid)s, tried to set %(num_metadata)s metadata "
"properties"
msgstr ""

#: nova/compute/api.py:160
#, python-format
msgid "Quota exceeded for %(pid)s, metadata property key or value too long"
msgstr ""

#: nova/compute/api.py:213
#, python-format
msgid "Quota exceeded for %(pid)s, tried to run %(min_count)s instances"
msgstr ""

#: nova/compute/api.py:216
msgid "Instance quota exceeded. You cannot run any more instances of this type."
msgstr ""

#: nova/compute/api.py:219
#, python-format
msgid "Instance quota exceeded. You can only run %s more instances of this type."
msgstr "Instance quota exceeded. You can only run %s more instances of this type."

#: nova/compute/api.py:268
msgid "Creating a raw instance"
msgstr "Creating a raw instance"

#: nova/compute/api.py:270
#, python-format
msgid "Using Kernel=%(kernel_id)s, Ramdisk=%(ramdisk_id)s"
msgstr ""

#: nova/compute/api.py:340
#, python-format
msgid "Going to run %s instances..."
msgstr "Going to run %s instances..."

#: nova/compute/api.py:404
#, python-format
msgid "bdm %s"
msgstr ""

#: nova/compute/api.py:431
#, python-format
msgid "block_device_mapping %s"
msgstr ""

#: nova/compute/api.py:548
#, python-format
msgid "Sending create to scheduler for %(pid)s/%(uid)s's"
msgstr ""

#: nova/compute/api.py:828
#, fuzzy, python-format
msgid "Going to try to soft delete instance"
msgstr "Going to try to terminate %s"

#: nova/compute/api.py:848
msgid "No host for instance, deleting immediately"
msgstr ""

#: nova/compute/api.py:882
#, fuzzy, python-format
msgid "Going to try to terminate instance"
msgstr "Going to try to terminate %s"

#: nova/compute/api.py:920
#, fuzzy, python-format
msgid "Going to try to stop instance"
msgstr "Going to try to terminate %s"

#: nova/compute/api.py:939
#, fuzzy, python-format
msgid "Going to try to start instance"
msgstr "Going to try to terminate %s"

#: nova/compute/api.py:943
#, python-format
msgid "Instance %(instance_uuid)s is not stopped. (%(vm_state)s"
msgstr ""

#: nova/compute/api.py:1009 nova/volume/api.py:163
#: nova/volume/volume_types.py:64
#, python-format
msgid "Searching by: %s"
msgstr ""

#: nova/compute/api.py:1300
msgid "flavor_id is None. Assuming migration."
msgstr ""

#: nova/compute/api.py:1308
#, python-format
msgid ""
"Old instance type %(current_instance_type_name)s,  new instance type "
"%(new_instance_type_name)s"
msgstr ""

#: nova/compute/api.py:1572
#, python-format
msgid "multiple fixedips exist, using the first: %s"
msgstr ""

#: nova/compute/api.py:1804
msgid "No compute host specified"
msgstr ""

#: nova/compute/api.py:1807
#, python-format
msgid "Unable to find host for Instance %s"
msgstr ""

#: nova/compute/instance_types.py:57 nova/compute/instance_types.py:65
msgid "create arguments must be positive integers"
msgstr ""

#: nova/compute/instance_types.py:74 nova/volume/volume_types.py:41
#, python-format
msgid "DB error: %s"
msgstr ""

#: nova/compute/instance_types.py:84
#, python-format
msgid "Instance type %s not found for deletion"
msgstr ""

#: nova/compute/manager.py:141
#, python-format
msgid "check_instance_lock: decorating: |%s|"
msgstr "check_instance_lock: decorating: |%s|"

#: nova/compute/manager.py:143
#, python-format
msgid ""
"check_instance_lock: arguments: |%(self)s| |%(context)s| "
"|%(instance_uuid)s|"
msgstr ""

#: nova/compute/manager.py:147
#, python-format
msgid "check_instance_lock: locked: |%s|"
msgstr "check_instance_lock: locked: |%s|"

#: nova/compute/manager.py:149
#, python-format
msgid "check_instance_lock: admin: |%s|"
msgstr "check_instance_lock: admin: |%s|"

#: nova/compute/manager.py:154
#, python-format
msgid "check_instance_lock: executing: |%s|"
msgstr "check_instance_lock: executing: |%s|"

#: nova/compute/manager.py:158
#, python-format
msgid "check_instance_lock: not executing |%s|"
msgstr "check_instance_lock: not executing |%s|"

#: nova/compute/manager.py:204
#, python-format
msgid "Unable to load the virtualization driver: %s"
msgstr ""

#: nova/compute/manager.py:239
#, python-format
msgid "Current state is %(drv_state)s, state in DB is %(db_state)s."
msgstr ""

#: nova/compute/manager.py:244
msgid "Rebooting instance after nova-compute restart."
msgstr ""

#: nova/compute/manager.py:254
msgid "Hypervisor driver does not support firewall rules"
msgstr ""

#: nova/compute/manager.py:259
msgid "Checking state"
msgstr ""

#: nova/compute/manager.py:328
#, python-format
msgid "Setting up bdm %s"
msgstr ""

#: nova/compute/manager.py:395
#, python-format
msgid ""
"Going to force the deletion of the vm %(instance_uuid)s, even if it is "
"deleted"
msgstr ""

#: nova/compute/manager.py:401
#, python-format
msgid ""
"Instance %(instance_uuid)s did not exist in the DB, but I will shut it "
"down anyway using a special context"
msgstr ""

#: nova/compute/manager.py:407
#, python-format
msgid "exception terminating the instance %(instance_uuid)s"
msgstr ""

#: nova/compute/manager.py:445
#, python-format
msgid "Instance %s not found."
msgstr ""

#: nova/compute/manager.py:481
msgid "Instance has already been created"
msgstr "Instance has already been created"

#: nova/compute/manager.py:524
#, python-format
msgid ""
"image_id=%(image_id)s, image_size_bytes=%(size_bytes)d, "
"allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: nova/compute/manager.py:529
#, python-format
msgid ""
"Image '%(image_id)s' size %(size_bytes)d exceeded instance_type allowed "
"size %(allowed_size_bytes)d"
msgstr ""

#: nova/compute/manager.py:539
msgid "Starting instance..."
msgstr ""

#: nova/compute/manager.py:549
msgid "Skipping network allocation for instance"
msgstr ""

#: nova/compute/manager.py:562
msgid "Instance failed network setup"
msgstr ""

#: nova/compute/manager.py:566
#, python-format
msgid "Instance network_info: |%s|"
msgstr ""

#: nova/compute/manager.py:579
msgid "Instance failed block device setup"
msgstr ""

#: nova/compute/manager.py:595
msgid "Instance failed to spawn"
msgstr ""

#: nova/compute/manager.py:616
msgid "Deallocating network for instance"
msgstr ""

#: nova/compute/manager.py:667
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: nova/compute/manager.py:679
#, python-format
msgid "trying to destroy already destroyed instance: %s"
msgstr "trying to destroy already destroyed instance: %s"

#: nova/compute/manager.py:699
#, python-format
msgid "Ignoring DiskNotFound: %s"
msgstr ""

#: nova/compute/manager.py:706
#, python-format
msgid "terminating bdm %s"
msgstr ""

#: nova/compute/manager.py:795
#, python-format
msgid ""
"Cannot rebuild instance [%(instance_uuid)s], because the given image does"
" not exist."
msgstr ""

#: nova/compute/manager.py:800
#, python-format
msgid "Cannot rebuild instance [%(instance_uuid)s]: %(exc)s"
msgstr ""

#: nova/compute/manager.py:807
#, python-format
msgid "Rebuilding instance %s"
msgstr ""

#: nova/compute/manager.py:860
#, python-format
msgid "Rebooting instance %s"
msgstr "Rebooting instance %s"

#: nova/compute/manager.py:875
#, python-format
msgid ""
"trying to reboot a non-running instance: %(instance_uuid)s (state: "
"%(state)s expected: %(running)s)"
msgstr ""

#: nova/compute/manager.py:913
#, python-format
msgid "Image type not recognized %s"
msgstr ""

#: nova/compute/manager.py:925
#, python-format
msgid "instance %s: snapshotting"
msgstr "instance %s: snapshotting"

#: nova/compute/manager.py:931
#, python-format
msgid ""
"trying to snapshot a non-running instance: %(instance_uuid)s (state: "
"%(state)s expected: %(running)s)"
msgstr ""

#: nova/compute/manager.py:984
#, python-format
msgid "Found %(num_images)d images (rotation: %(rotation)d)"
msgstr ""

#: nova/compute/manager.py:989
#, python-format
msgid "Rotating out %d backups"
msgstr ""

#: nova/compute/manager.py:993
#, python-format
msgid "Deleting image %s"
msgstr ""

#: nova/compute/manager.py:1023
#, python-format
msgid "Failed to set admin password. Instance %s is not running"
msgstr ""

#: nova/compute/manager.py:1029
#, python-format
msgid "Instance %s: Root password set"
msgstr ""

#: nova/compute/manager.py:1038
msgid "set_admin_password is not implemented by this driver."
msgstr ""

#: nova/compute/manager.py:1052
msgid "Error setting admin password"
msgstr ""

#: nova/compute/manager.py:1067
#, python-format
msgid ""
"trying to inject a file into a non-running instance: %(instance_uuid)s "
"(state: %(current_power_state)s expected: %(expected_state)s)"
msgstr ""

#: nova/compute/manager.py:1072
#, python-format
msgid "instance %(instance_uuid)s: injecting file to %(path)s"
msgstr ""

#: nova/compute/manager.py:1086
#, python-format
msgid ""
"trying to update agent on a non-running instance: %(instance_uuid)s "
"(state: %(current_power_state)s expected: %(expected_state)s)"
msgstr ""

#: nova/compute/manager.py:1091
#, python-format
msgid "instance %(instance_uuid)s: updating agent to %(url)s"
msgstr ""

#: nova/compute/manager.py:1104
#, python-format
msgid "instance %s: rescuing"
msgstr "instance %s: rescuing"

#: nova/compute/manager.py:1129
#, python-format
msgid "instance %s: unrescuing"
msgstr "instance %s: unrescuing"

#: nova/compute/manager.py:1248
msgid "destination same as source!"
msgstr ""

#: nova/compute/manager.py:1265
#, python-format
msgid "instance %s: migrating"
msgstr ""

#: nova/compute/manager.py:1302 nova/compute/manager.py:1377
#: nova/compute/manager.py:2395
#, python-format
msgid "%s. Setting instance vm_state to ERROR"
msgstr ""

#: nova/compute/manager.py:1430
#, python-format
msgid "instance %s: pausing"
msgstr "instance %s: pausing"

#: nova/compute/manager.py:1448
#, python-format
msgid "instance %s: unpausing"
msgstr "instance %s: unpausing"

#: nova/compute/manager.py:1484
#, python-format
msgid "instance %s: retrieving diagnostics"
msgstr "instance %s: retrieving diagnostics"

#: nova/compute/manager.py:1493
#, python-format
msgid "instance %s: suspending"
msgstr "instance %s: suspending"

#: nova/compute/manager.py:1515
#, python-format
msgid "instance %s: resuming"
msgstr "instance %s: resuming"

#: nova/compute/manager.py:1538
#, python-format
msgid "instance %s: locking"
msgstr "instance %s: locking"

#: nova/compute/manager.py:1547
#, python-format
msgid "instance %s: unlocking"
msgstr "instance %s: unlocking"

#: nova/compute/manager.py:1555
#, python-format
msgid "instance %s: getting locked state"
msgstr "instance %s: getting locked state"

#: nova/compute/manager.py:1565
#, python-format
msgid "instance %s: reset network"
msgstr "instance %s: reset network"

#: nova/compute/manager.py:1573
#, python-format
msgid "instance %s: inject network info"
msgstr ""

#: nova/compute/manager.py:1577
#, python-format
msgid "network_info to inject: |%s|"
msgstr ""

#: nova/compute/manager.py:1614
#, python-format
msgid "instance %s: getting vnc console"
msgstr ""

#: nova/compute/manager.py:1644
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:1662
#, python-format
msgid ""
"instance %(instance_uuid)s: attaching volume %(volume_id)s to "
"%(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:1664
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:1673
#, python-format
msgid "instance %(instance_uuid)s: attach failed %(mountpoint)s, removing"
msgstr ""

#: nova/compute/manager.py:1683
#, python-format
msgid "Attach failed %(mountpoint)s, removing"
msgstr ""

#: nova/compute/manager.py:1711
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:1715
#, python-format
msgid "Detaching volume from unknown instance %s"
msgstr "Detaching volume from unknown instance %s"

#: nova/compute/manager.py:1781
#, python-format
msgid ""
"Creating tmpfile %s to notify to other compute nodes that they should "
"mount the same storage."
msgstr ""

#: nova/compute/manager.py:1843
msgid "Instance has no volume."
msgstr ""

#: nova/compute/manager.py:1871
#, python-format
msgid "plug_vifs() failed %(cnt)d.Retry up to %(max_retry)d for %(hostname)s."
msgstr ""

#: nova/compute/manager.py:1928
#, python-format
msgid "Pre live migration failed at  %(dest)s"
msgstr ""

#: nova/compute/manager.py:1955
msgid "post_live_migration() is started.."
msgstr ""

#: nova/compute/manager.py:1985
msgid "No floating_ip found"
msgstr ""

#: nova/compute/manager.py:1993
msgid "No floating_ip found."
msgstr ""

#: nova/compute/manager.py:1995
#, python-format
msgid ""
"Live migration: Unexpected error: cannot inherit floating ip.\n"
"%(e)s"
msgstr ""

#: nova/compute/manager.py:2033
#, python-format
msgid "Migrating instance to %(dest)s finished successfully."
msgstr ""

#: nova/compute/manager.py:2035
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: nova/compute/manager.py:2050
msgid "Post operation of migraton started"
msgstr ""

#: nova/compute/manager.py:2157
#, python-format
msgid "Updated the info_cache for instance %s"
msgstr ""

#: nova/compute/manager.py:2186
msgid "Updating bandwidth usage cache"
msgstr ""

#: nova/compute/manager.py:2213
msgid "Updating host status"
msgstr ""

#: nova/compute/manager.py:2241
#, python-format
msgid ""
"Found %(num_db_instances)s in the database and %(num_vm_instances)s on "
"the hypervisor."
msgstr ""

#: nova/compute/manager.py:2252
msgid ""
"Instance found in database but not known by hypervisor. Setting power "
"state to NOSTATE"
msgstr ""

#: nova/compute/manager.py:2275
msgid "FLAGS.reclaim_instance_interval <= 0, skipping..."
msgstr ""

#: nova/compute/manager.py:2287
msgid "Reclaiming deleted instance"
msgstr ""

#: nova/compute/manager.py:2352
#, python-format
msgid ""
"Detected instance  with name label '%(name_label)s' which is marked as "
"DELETED but still present on host."
msgstr ""

#: nova/compute/manager.py:2359
#, python-format
msgid ""
"Destroying instance with name label '%(name)s' which is marked as DELETED"
" but still present on host."
msgstr ""

#: nova/compute/manager.py:2366
#, python-format
msgid "Unrecognized value '%(action)s' for FLAGS.running_deleted_instance_action"
msgstr ""

#: nova/compute/manager.py:2436
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on "
"%(host)s"
msgstr ""

#: nova/compute/utils.py:141
msgid "v4 subnets are required for legacy nw_info"
msgstr ""

#: nova/console/manager.py:77 nova/console/vmrc_manager.py:70
msgid "Adding console"
msgstr "Adding console"

#: nova/console/manager.py:97
#, python-format
msgid "Tried to remove non-existant console %(console_id)s."
msgstr "Tried to remove non-existent console %(console_id)s."

#: nova/console/vmrc_manager.py:122
#, python-format
msgid "Tried to remove non-existent console %(console_id)s."
msgstr ""

#: nova/console/vmrc_manager.py:125
#, python-format
msgid "Removing console %(console_id)s."
msgstr ""

#: nova/console/xvp.py:98
msgid "Rebuilding xvp conf"
msgstr "Rebuilding xvp conf"

#: nova/console/xvp.py:116
#, python-format
msgid "Re-wrote %s"
msgstr "Re-wrote %s"

#: nova/console/xvp.py:121
msgid "Stopping xvp"
msgstr "Stopping xvp"

#: nova/console/xvp.py:134
msgid "Starting xvp"
msgstr "Starting xvp"

#: nova/console/xvp.py:141
#, python-format
msgid "Error starting xvp: %s"
msgstr "Error starting xvp: %s"

#: nova/console/xvp.py:144
msgid "Restarting xvp"
msgstr "Restarting xvp"

#: nova/console/xvp.py:146
msgid "xvp not running..."
msgstr "xvp not running..."

#: nova/consoleauth/manager.py:63
#, python-format
msgid "Deleting Expired Token: (%s)"
msgstr ""

#: nova/consoleauth/manager.py:75
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s)"
msgstr ""

#: nova/consoleauth/manager.py:79
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s)"
msgstr ""

#: nova/db/sqlalchemy/api.py:56
msgid "Use of empty request context is deprecated"
msgstr "Use of empty request context is deprecated"

#: nova/db/sqlalchemy/api.py:188
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: nova/db/sqlalchemy/api.py:566 nova/db/sqlalchemy/api.py:601
#, python-format
msgid "No ComputeNode for %(host)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4162 nova/db/sqlalchemy/api.py:4188
#, python-format
msgid "No backend config with id %(sm_backend_id)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4246
#, python-format
msgid "No sm_flavor called %(sm_flavor)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:4290
#, python-format
msgid "No sm_volume with id %(volume_id)s"
msgstr ""

#: nova/db/sqlalchemy/migration.py:36
msgid "python-migrate is not installed. Exiting."
msgstr "python-migrate is not installed. Exiting."

#: nova/db/sqlalchemy/migration.py:46
msgid "version should be an integer"
msgstr ""

#: nova/db/sqlalchemy/session.py:87
#, python-format
msgid "SQL connection failed (%(connstring)s). %(attempts)d attempts left."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:48
msgid "interface column not added to networks table"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:80
#: nova/db/sqlalchemy/migrate_repo/versions/062_add_instance_info_cache_table.py:54
#: nova/db/sqlalchemy/migrate_repo/versions/072_add_dns_table.py:61
#, python-format
msgid "Table |%s| not created!"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:87
msgid "VIF column not added to fixed_ips table"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/030_multi_nic.py:97
#, python-format
msgid "join list for moving mac_addresses |%s|"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/031_fk_fixed_ips_virtual_interface_id.py:39
#: nova/db/sqlalchemy/migrate_repo/versions/047_remove_instances_fk_from_vif.py:60
#: nova/db/sqlalchemy/migrate_repo/versions/060_remove_network_fk_from_vif.py:61
#: nova/db/sqlalchemy/migrate_repo/versions/070_untie_nova_network_models.py:99
msgid "foreign key constraint couldn't be added"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/031_fk_fixed_ips_virtual_interface_id.py:58
msgid "foreign key constraint couldn't be dropped"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/045_add_network_priority.py:34
msgid "priority column not added to networks table"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/047_remove_instances_fk_from_vif.py:41
#: nova/db/sqlalchemy/migrate_repo/versions/060_remove_network_fk_from_vif.py:42
#: nova/db/sqlalchemy/migrate_repo/versions/064_change_instance_id_to_uuid_in_instance_actions.py:56
#: nova/db/sqlalchemy/migrate_repo/versions/070_untie_nova_network_models.py:68
msgid "foreign key constraint couldn't be removed"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/049_add_instances_progress.py:34
msgid "progress column not added to instances table"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/055_convert_flavor_id_to_str.py:97
#, python-format
msgid ""
"Could not cast flavorid to integer: %s. Set flavorid to an integer-like "
"string to downgrade."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/062_add_instance_info_cache_table.py:69
msgid "instance_info_caches tables not dropped"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/069_block_migration.py:41
msgid "progress column not added to compute_nodes table"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/072_add_dns_table.py:76
msgid "dns_domains table not dropped"
msgstr ""

#: nova/image/glance.py:147
msgid "Connection error contacting glance server, retrying"
msgstr ""

#: nova/image/glance.py:153 nova/network/quantum/melange_connection.py:103
msgid "Maximum attempts reached"
msgstr ""

#: nova/image/glance.py:275
#, python-format
msgid "Creating image in Glance. Metadata passed in %s"
msgstr ""

#: nova/image/glance.py:278
#, python-format
msgid "Metadata after formatting for Glance %s"
msgstr ""

#: nova/image/glance.py:286
#, python-format
msgid "Metadata returned from Glance formatted for Base %s"
msgstr ""

#: nova/image/glance.py:328 nova/image/glance.py:332
msgid "Not the image owner"
msgstr ""

#: nova/image/glance.py:407
#, python-format
msgid "%(timestamp)s does not follow any of the signatures: %(iso_formats)s"
msgstr ""

#: nova/image/s3.py:296
#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:315
#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:327
#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:340
#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr ""

#: nova/image/s3.py:366
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr "Failed to decrypt private key: %s"

#: nova/image/s3.py:374
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr "Failed to decrypt initialisation vector: %s"

#: nova/image/s3.py:385
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr "Failed to decrypt image file %(image_file)s: %(err)s"

#: nova/image/s3.py:397
msgid "Unsafe filenames in image"
msgstr ""

#: nova/ipv6/account_identifier.py:38 nova/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:40 nova/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:42
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr ""

#: nova/network/ldapdns.py:321
msgid "This driver only supports type 'a' entries."
msgstr ""

#: nova/network/linux_net.py:167
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: nova/network/linux_net.py:193
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: nova/network/linux_net.py:216
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: nova/network/linux_net.py:336
msgid "IPTablesManager.apply completed with success"
msgstr ""

#: nova/network/linux_net.py:587 nova/network/linux_net.py:609
#: nova/network/linux_net.py:651
#, python-format
msgid "Instance %(instance_id)s not found"
msgstr ""

#: nova/network/linux_net.py:718
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr "Hupping dnsmasq threw %s"

#: nova/network/linux_net.py:720
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr "Pid %d is stale, relaunching dnsmasq"

#: nova/network/linux_net.py:780
#, python-format
msgid "killing radvd threw %s"
msgstr "killing radvd threw %s"

#: nova/network/linux_net.py:782
#, python-format
msgid "Pid %d is stale, relaunching radvd"
msgstr "Pid %d is stale, relaunching radvd"

#: nova/network/linux_net.py:984
#, python-format
msgid "Starting VLAN inteface %s"
msgstr "Starting VLAN inteface %s"

#: nova/network/linux_net.py:1016
#, python-format
msgid "Starting Bridge interface for %s"
msgstr "Starting Bridge interface for %s"

#: nova/network/manager.py:273 nova/network/manager.py:471
#, python-format
msgid "Interface %(interface)s not found"
msgstr ""

#: nova/network/manager.py:288
#, python-format
msgid "floating IP allocation for instance |%s|"
msgstr ""

#: nova/network/manager.py:328
#, python-format
msgid "floating IP deallocation for instance |%s|"
msgstr ""

#: nova/network/manager.py:361
#, python-format
msgid "Address |%(address)s| is not allocated"
msgstr ""

#: nova/network/manager.py:365
#, python-format
msgid "Address |%(address)s| is not allocated to your project |%(project)s|"
msgstr ""

#: nova/network/manager.py:377
#, python-format
msgid "Quota exceeded for %s, tried to allocate address"
msgstr ""

#: nova/network/manager.py:589
#, python-format
msgid ""
"Database inconsistency: DNS domain |%s| is registered in the Nova db but "
"not visible to either the floating or instance DNS driver. It will be "
"ignored."
msgstr ""

#: nova/network/manager.py:635
#, python-format
msgid "Domain |%(domain)s| already exists, changing zone to |%(av_zone)s|."
msgstr ""

#: nova/network/manager.py:645
#, python-format
msgid "Domain |%(domain)s| already exists, changing project to |%(project)s|."
msgstr ""

#: nova/network/manager.py:753
#, python-format
msgid "Disassociated %s stale fixed ip(s)"
msgstr ""

#: nova/network/manager.py:757
msgid "setting network host"
msgstr "setting network host"

#: nova/network/manager.py:871
#, python-format
msgid "network allocations for instance |%s|"
msgstr ""

#: nova/network/manager.py:876
#, python-format
msgid "networks retrieved for instance |%(instance_id)s|: |%(networks)s|"
msgstr ""

#: nova/network/manager.py:905
#, python-format
msgid "network deallocation for instance |%s|"
msgstr ""

#: nova/network/manager.py:1126
#, python-format
msgid ""
"instance-dns-zone is |%(domain)s|, which is in availability zone "
"|%(zone)s|. Instance |%(instance)s| is in zone |%(zone2)s|. No DNS record"
" will be created."
msgstr ""

#: nova/network/manager.py:1201
#, python-format
msgid "Leased IP |%(address)s|"
msgstr ""

#: nova/network/manager.py:1205
#, python-format
msgid "IP %s leased that is not associated"
msgstr ""

#: nova/network/manager.py:1213
#, python-format
msgid "IP |%s| leased that isn't allocated"
msgstr ""

#: nova/network/manager.py:1218
#, python-format
msgid "Released IP |%(address)s|"
msgstr ""

#: nova/network/manager.py:1222
#, python-format
msgid "IP %s released that is not associated"
msgstr ""

#: nova/network/manager.py:1225
#, python-format
msgid "IP %s released that was not leased"
msgstr "IP %s released that was not leased"

#: nova/network/manager.py:1294
msgid "cidr already in use"
msgstr ""

#: nova/network/manager.py:1297
#, python-format
msgid "requested cidr (%(cidr)s) conflicts with existing supernet (%(super)s)"
msgstr ""

#: nova/network/manager.py:1308
#, python-format
msgid ""
"requested cidr (%(cidr)s) conflicts with existing smaller cidr "
"(%(smaller)s)"
msgstr ""

#: nova/network/manager.py:1367
msgid "Network already exists!"
msgstr ""

#: nova/network/manager.py:1386
#, python-format
msgid "Network must be disassociated from project %s before delete"
msgstr ""

#: nova/network/manager.py:1703
msgid ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"
msgstr ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"

#: nova/network/manager.py:1710
#, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s. Network size"
" is %(network_size)s"
msgstr ""

#: nova/network/minidns.py:65
msgid "This driver only supports type 'a'"
msgstr ""

#: nova/network/quantum/client.py:154
msgid "Tenant ID not set"
msgstr ""

#: nova/network/quantum/client.py:181
#, python-format
msgid "Quantum Client Request: %(method)s %(action)s"
msgstr ""

#: nova/network/quantum/client.py:196
#, python-format
msgid "Quantum entity not found: %s"
msgstr ""

#: nova/network/quantum/client.py:207
#, python-format
msgid "Server %(status_code)s error: %(data)s"
msgstr ""

#: nova/network/quantum/client.py:210
#, python-format
msgid "Unable to connect to server. Got error: %s"
msgstr ""

#: nova/network/quantum/client.py:229
#, python-format
msgid "unable to deserialize object of type = '%s'"
msgstr ""

#: nova/network/quantum/manager.py:151
msgid "QuantumManager does not use 'multi_host' parameter."
msgstr ""

#: nova/network/quantum/manager.py:155
msgid "QuantumManager requires that only one network is created per call"
msgstr ""

#: nova/network/quantum/manager.py:165
msgid "QuantumManager does not use 'vlan_start' parameter."
msgstr ""

#: nova/network/quantum/manager.py:171
msgid "QuantumManager does not use 'vpn_start' parameter."
msgstr ""

#: nova/network/quantum/manager.py:175
msgid "QuantumManager does not use 'bridge' parameter."
msgstr ""

#: nova/network/quantum/manager.py:179
msgid "QuantumManager does not use 'bridge_interface' parameter."
msgstr ""

#: nova/network/quantum/manager.py:184
msgid "QuantumManager requires a valid (.1) gateway address."
msgstr ""

#: nova/network/quantum/manager.py:196
#, python-format
msgid ""
"Unable to find existing quantum network for tenant '%(q_tenant_id)s' with"
" net-id '%(quantum_net_id)s'"
msgstr ""

#: nova/network/quantum/manager.py:242
#, python-format
msgid "Network %s has active ports, cannot delete"
msgstr ""

#: nova/network/quantum/manager.py:288
#, python-format
msgid "network allocations for instance %s"
msgstr ""

#: nova/network/quantum/manager.py:564
#, python-format
msgid ""
"port deallocation failed for instance: |%(instance_id)s|, port_id: "
"|%(port_id)s|"
msgstr ""

#: nova/network/quantum/manager.py:583
#, python-format
msgid ""
"ipam deallocation failed for instance: |%(instance_id)s|, vif_uuid: "
"|%(vif_uuid)s|"
msgstr ""

#: nova/network/quantum/melange_connection.py:95
#, python-format
msgid "Server returned error: %s"
msgstr ""

#: nova/network/quantum/melange_connection.py:97
msgid "Connection error contacting melange service, retrying"
msgstr ""

#: nova/network/quantum/melange_connection.py:107
#, python-format
msgid ""
"allocate IP on network |%(network_id)s| belonging to "
"|%(network_tenant_id)s| to this vif |%(vif_id)s| with mac "
"|%(mac_address)s| belonging to |%(project_id)s| "
msgstr ""

#: nova/network/quantum/melange_ipam_lib.py:132
msgid "get_project_and_global_net_ids must be called with a non-null project_id"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:75
msgid "Error creating network entry"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:90
#, python-format
msgid "No network with net_id = %s"
msgstr ""

#: nova/network/quantum/nova_ipam_lib.py:221
#, python-format
msgid "No fixed IPs to deallocate for vif %sid"
msgstr ""

#: nova/network/quantum/quantum_connection.py:100
#, python-format
msgid "Connecting interface %(interface_id)s to net %(net_id)s for %(tenant_id)s"
msgstr ""

#: nova/network/quantum/quantum_connection.py:114
#, python-format
msgid "Deleting port %(port_id)s on net %(net_id)s for %(tenant_id)s"
msgstr ""

#: nova/notifier/api.py:115
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: nova/notifier/api.py:132
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: nova/notifier/list_notifier.py:65
#, python-format
msgid "Problem '%(e)s' attempting to send to notification driver %(driver)s."
msgstr ""

#: nova/notifier/rabbit_notifier.py:44
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: nova/rpc/amqp.py:144 nova/rpc/impl_carrot.py:460
#, python-format
msgid "Returning exception %s to caller"
msgstr "Returning exception %s to caller"

#: nova/rpc/amqp.py:186 nova/rpc/impl_carrot.py:494
#, python-format
msgid "unpacked context: %s"
msgstr "unpacked context: %s"

#: nova/rpc/amqp.py:229 nova/rpc/impl_carrot.py:261
#, python-format
msgid "received %s"
msgstr "received %s"

#: nova/rpc/amqp.py:234 nova/rpc/impl_carrot.py:274
#, python-format
msgid "no method for message: %s"
msgstr "no method for message: %s"

#: nova/rpc/amqp.py:235 nova/rpc/impl_carrot.py:276
#, python-format
msgid "No method for message: %s"
msgstr "No method for message: %s"

#: nova/rpc/amqp.py:319 nova/rpc/impl_carrot.py:528
#, python-format
msgid "Making asynchronous call on %s ..."
msgstr ""

#: nova/rpc/amqp.py:322 nova/rpc/impl_carrot.py:531
#, python-format
msgid "MSG_ID is %s"
msgstr "MSG_ID is %s"

#: nova/rpc/amqp.py:344 nova/rpc/impl_carrot.py:610
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: nova/rpc/amqp.py:352 nova/rpc/impl_carrot.py:620
msgid "Making asynchronous fanout cast..."
msgstr ""

#: nova/rpc/amqp.py:377 nova/rpc/impl_carrot.py:630
#, python-format
msgid "Sending notification on %s..."
msgstr ""

#: nova/rpc/common.py:54
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: nova/rpc/common.py:71
msgid "Timeout while waiting on RPC response."
msgstr ""

#: nova/rpc/impl_carrot.py:198
#, python-format
msgid ""
"AMQP server on %(fl_host)s:%(fl_port)d is unreachable: %(e)s. Trying "
"again in %(fl_intv)d seconds."
msgstr ""

#: nova/rpc/impl_carrot.py:202
#, python-format
msgid "Unable to connect to AMQP server after %(tries)d tries. Shutting down."
msgstr ""

#: nova/rpc/impl_carrot.py:222
msgid "Reconnected to queue"
msgstr "Reconnected to queue"

#: nova/rpc/impl_carrot.py:229
#, python-format
msgid "Failed to fetch message from queue: %s"
msgstr ""

#: nova/rpc/impl_carrot.py:237
#, python-format
msgid "Initing the Adapter Consumer for %s"
msgstr "Initing the Adapter Consumer for %s"

#: nova/rpc/impl_carrot.py:336
#, python-format
msgid "Created \"%(exchange)s\" fanout exchange with \"%(key)s\" routing key"
msgstr ""

#: nova/rpc/impl_carrot.py:381
msgid "Exception while processing consumer"
msgstr ""

#: nova/rpc/impl_carrot.py:418
#, python-format
msgid "Creating \"%(exchange)s\" fanout exchange"
msgstr ""

#: nova/rpc/impl_carrot.py:645
#, python-format
msgid "response %s"
msgstr "response %s"

#: nova/rpc/impl_carrot.py:654
#, python-format
msgid "topic is %s"
msgstr "topic is %s"

#: nova/rpc/impl_carrot.py:655
#, python-format
msgid "message %s"
msgstr "message %s"

#: nova/rpc/impl_kombu.py:357
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: nova/rpc/impl_kombu.py:380
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: nova/rpc/impl_kombu.py:416
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: nova/rpc/impl_kombu.py:432
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: nova/rpc/impl_kombu.py:483 nova/rpc/impl_qpid.py:384
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: nova/rpc/impl_kombu.py:501 nova/rpc/impl_qpid.py:399
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: nova/rpc/impl_kombu.py:505 nova/rpc/impl_qpid.py:403
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: nova/rpc/impl_kombu.py:539 nova/rpc/impl_qpid.py:430
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: nova/rpc/impl_qpid.py:340
#, python-format
msgid "Unable to connect to AMQP server: %s "
msgstr ""

#: nova/rpc/impl_qpid.py:345
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: nova/rpc/impl_qpid.py:353
msgid "Re-established AMQP queues"
msgstr ""

#: nova/scheduler/chance.py:47 nova/scheduler/simple.py:91
#: nova/scheduler/simple.py:142
msgid "Is the appropriate service running?"
msgstr ""

#: nova/scheduler/chance.py:52
msgid "Could not find another compute"
msgstr ""

#: nova/scheduler/distributed_scheduler.py:51
#, python-format
msgid "No host selection for %s defined."
msgstr ""

#: nova/scheduler/distributed_scheduler.py:64
#, python-format
msgid "Attempting to build %(num_instances)d instance(s)"
msgstr ""

#: nova/scheduler/distributed_scheduler.py:156
msgid "Scheduler only understands Compute nodes (for now)"
msgstr ""

#: nova/scheduler/distributed_scheduler.py:198
#, python-format
msgid "Filtered %(hosts)s"
msgstr ""

#: nova/scheduler/distributed_scheduler.py:208
#, python-format
msgid "Weighted %(weighted_host)s"
msgstr ""

#: nova/scheduler/driver.py:63
#, python-format
msgid "Casted '%(method)s' to volume '%(host)s'"
msgstr ""

#: nova/scheduler/driver.py:80
#, python-format
msgid "Casted '%(method)s' to compute '%(host)s'"
msgstr ""

#: nova/scheduler/driver.py:89
#, python-format
msgid "Casted '%(method)s' to network '%(host)s'"
msgstr ""

#: nova/scheduler/driver.py:107
#, python-format
msgid "Casted '%(method)s' to %(topic)s '%(host)s'"
msgstr ""

#: nova/scheduler/driver.py:181
msgid "Must implement a fallback schedule"
msgstr "Must implement a fallback schedule"

#: nova/scheduler/driver.py:314
msgid "Block migration can not be used with shared storage."
msgstr ""

#: nova/scheduler/driver.py:322
#, python-format
msgid ""
"Cannot confirm tmpfile at %(ipath)s is on same shared storage between "
"%(src)s and %(dest)s."
msgstr ""

#: nova/scheduler/driver.py:360 nova/scheduler/driver.py:450
#, python-format
msgid "host %(dest)s is not compatible with original host %(src)s."
msgstr ""

#: nova/scheduler/driver.py:409
#, python-format
msgid ""
"Unable to migrate %(instance_id)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""

#: nova/scheduler/driver.py:465
#, python-format
msgid ""
"Unable to migrate %(instance_id)s to %(dest)s: Lack of "
"disk(host:%(available)s <= instance:%(necessary)s)"
msgstr ""

#: nova/scheduler/host_manager.py:265
#, python-format
msgid "Received %(service_name)s service update from %(host)s."
msgstr ""

#: nova/scheduler/host_manager.py:306
msgid "host_manager only implemented for 'compute'"
msgstr ""

#: nova/scheduler/host_manager.py:316
#, python-format
msgid "No service for compute ID %s"
msgstr ""

#: nova/scheduler/manager.py:86
#, python-format
msgid "Driver Method %(driver_method)s missing: %(e)s.Reverting to schedule()"
msgstr ""

#: nova/scheduler/manager.py:102
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: nova/scheduler/manager.py:117
#, python-format
msgid "Setting instance %(instance_uuid)s to ERROR state."
msgstr ""

#: nova/scheduler/scheduler_options.py:67
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: nova/scheduler/scheduler_options.py:75
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: nova/scheduler/simple.py:87
msgid "Not enough allocatable CPU cores remaining"
msgstr ""

#: nova/scheduler/simple.py:136
msgid "Not enough allocatable volume gigabytes remaining"
msgstr ""

#: nova/scheduler/vsa.py:112
#, python-format
msgid "_filter_hosts: %(request_spec)s"
msgstr ""

#: nova/scheduler/vsa.py:115
#, python-format
msgid "Filter hosts for drive type %s"
msgstr ""

#: nova/scheduler/vsa.py:132
#, python-format
msgid "Host %s has no free capacity. Skip"
msgstr ""

#: nova/scheduler/vsa.py:137
#, python-format
msgid "Filter hosts: %s"
msgstr ""

#: nova/scheduler/vsa.py:153
msgid "Must implement host selection mechanism"
msgstr ""

#: nova/scheduler/vsa.py:163
#, python-format
msgid "Maximum number of hosts selected (%d)"
msgstr ""

#: nova/scheduler/vsa.py:171
#, python-format
msgid "Selected excessive host %(host)s"
msgstr ""

#: nova/scheduler/vsa.py:211
#, python-format
msgid "Provision volume %(name)s of size %(size)s GB on host %(host)s"
msgstr ""

#: nova/scheduler/vsa.py:239
#, python-format
msgid "volume_params %(volume_params)s"
msgstr ""

#: nova/scheduler/vsa.py:244
#, python-format
msgid "%(i)d: Volume %(name)s"
msgstr ""

#: nova/scheduler/vsa.py:282
#, python-format
msgid "Attempting to spawn %(num_volumes)d volume(s)"
msgstr ""

#: nova/scheduler/vsa.py:298
msgid "Error creating volumes"
msgstr ""

#: nova/scheduler/vsa.py:328
#, python-format
msgid "Non-VSA volume %d"
msgstr ""

#: nova/scheduler/vsa.py:341
#, python-format
msgid "Spawning volume %(volume_id)s with drive type %(drive_type)s"
msgstr ""

#: nova/scheduler/vsa.py:351
msgid "Error creating volume"
msgstr ""

#: nova/scheduler/vsa.py:391
#, python-format
msgid "No capability selected for volume of size %(size)s"
msgstr ""

#: nova/scheduler/vsa.py:411
#, python-format
msgid "Host %s:"
msgstr ""

#: nova/scheduler/vsa.py:420
#, python-format
msgid ""
"\tDrive %(qosgrp)-25s: total %(total)2s, used %(used)2s, free %(free)2s. "
"Available capacity %(avail)-5s"
msgstr ""

#: nova/scheduler/vsa.py:483
#, python-format
msgid "\t LeastUsedHost: Best host: %(best_host)s. (used capacity %(min_used)s)"
msgstr ""

#: nova/scheduler/vsa.py:528
#, python-format
msgid ""
"\t MostAvailCap: Best host: %(best_host)s. (available %(max_avail)s "
"%(type_str)s)"
msgstr ""

#: nova/scheduler/filters/core_filter.py:45
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: nova/testing/fake/rabbit.py:50
#, python-format
msgid "(%(nm)s) publish (key: %(routing_key)s) %(message)s"
msgstr "(%(nm)s) publish (key: %(routing_key)s) %(message)s"

#: nova/testing/fake/rabbit.py:54
#, python-format
msgid "Publishing to route %s"
msgstr "Publishing to route %s"

#: nova/testing/fake/rabbit.py:84
#, python-format
msgid "Declaring queue %s"
msgstr "Declaring queue %s"

#: nova/testing/fake/rabbit.py:90
#, python-format
msgid "Declaring exchange %s"
msgstr "Declaring exchange %s"

#: nova/testing/fake/rabbit.py:96
#, python-format
msgid "Binding %(queue)s to %(exchange)s with key %(routing_key)s"
msgstr "Binding %(queue)s to %(exchange)s with key %(routing_key)s"

#: nova/testing/fake/rabbit.py:133
#, python-format
msgid "Getting from %(queue)s: %(message)s"
msgstr "Getting from %(queue)s: %(message)s"

#: nova/tests/fake_utils.py:72
#, python-format
msgid "Faking execution of cmd (subprocess): %s"
msgstr ""

#: nova/tests/fake_utils.py:80
#, python-format
msgid "Faked command matched %s"
msgstr ""

#: nova/tests/fake_utils.py:96
#, python-format
msgid "Faked command raised an exception %s"
msgstr ""

#: nova/tests/fake_utils.py:101
#, python-format
msgid "Reply to faked command is stdout='%(stdout)s' stderr='%(stderr)s'"
msgstr ""

#: nova/tests/fakelibvirt.py:774
msgid "Please extend mock libvirt module to support flags"
msgstr ""

#: nova/tests/fakelibvirt.py:780
msgid "Please extend fake libvirt module to support this auth method"
msgstr ""

#: nova/tests/test_compute.py:382 nova/tests/test_compute.py:1491
#, python-format
msgid "Running instances: %s"
msgstr "Running instances: %s"

#: nova/tests/test_compute.py:388
#, python-format
msgid "After terminating instances: %s"
msgstr "After terminating instances: %s"

#: nova/tests/test_compute.py:612
msgid "Internal error"
msgstr ""

#: nova/tests/test_compute.py:1502
#, python-format
msgid "After force-killing instances: %s"
msgstr ""

#: nova/tests/test_misc.py:114
#, python-format
msgid ""
"The following migrations are missing a downgrade:\n"
"\t%s"
msgstr ""

#: nova/tests/test_nova_manage.py:182
msgid "id"
msgstr ""

#: nova/tests/test_nova_manage.py:183
msgid "IPv4"
msgstr ""

#: nova/tests/test_nova_manage.py:184
msgid "IPv6"
msgstr ""

#: nova/tests/test_nova_manage.py:185
msgid "start address"
msgstr "start address"

#: nova/tests/test_nova_manage.py:186
msgid "DNS1"
msgstr ""

#: nova/tests/test_nova_manage.py:187
msgid "DNS2"
msgstr ""

#: nova/tests/test_nova_manage.py:188
msgid "VlanID"
msgstr ""

#: nova/tests/test_nova_manage.py:189
msgid "project"
msgstr ""

#: nova/tests/test_nova_manage.py:190
msgid "uuid"
msgstr ""

#: nova/tests/test_volume.py:216
#, python-format
msgid "Target %s allocated"
msgstr "Target %s allocated"

#: nova/tests/test_volume.py:425
#, python-format
msgid "Cannot confirm exported volume id:%s."
msgstr ""

#: nova/tests/test_volume_types.py:60
#, python-format
msgid "Given data: %s"
msgstr ""

#: nova/tests/test_volume_types.py:61
#, python-format
msgid "Result data: %s"
msgstr ""

#: nova/tests/test_vsa.py:57
msgid "Test: Emulate wrong VSA name. Raise"
msgstr ""

#: nova/tests/test_vsa.py:99
msgid "Test: Emulate DB error. Raise"
msgstr ""

#: nova/tests/test_vsa.py:167
#, python-format
msgid "Test: user_data = %s"
msgstr ""

#: nova/tests/test_xenapi.py:620
#, python-format
msgid "Creating files in %s to simulate guest agent"
msgstr ""

#: nova/tests/test_xenapi.py:631
#, python-format
msgid "Removing simulated guest agent files in %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:58
#, python-format
msgid "_create: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:67
#: nova/tests/api/openstack/compute/contrib/test_vsa.py:70
#, python-format
msgid "_delete: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:76
#: nova/tests/api/openstack/compute/contrib/test_vsa.py:79
#, python-format
msgid "_get: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:86
#: nova/tests/api/openstack/compute/contrib/test_vsa.py:89
#, python-format
msgid "_get_all: %s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:131
#, python-format
msgid "test_snapshot_create: param=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:140
#, python-format
msgid "test_snapshot_create: resp_dict=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:162
#, python-format
msgid "test_snapshot_create_force: param=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:171
#, python-format
msgid "test_snapshot_create_force: resp_dict=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:211
#, python-format
msgid "test_snapshot_show: resp=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_snapshots.py:237
#, python-format
msgid "test_snapshot_detail: resp_dict=%s"
msgstr ""

#: nova/tests/api/openstack/compute/contrib/test_vsa.py:58
#, python-format
msgid "_create: param=%s"
msgstr ""

#: nova/tests/integrated/test_login.py:31
#, python-format
msgid "flavor: %s"
msgstr ""

#: nova/tests/integrated/api/client.py:38
#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""

#: nova/tests/integrated/api/client.py:47
msgid "Authentication error"
msgstr ""

#: nova/tests/integrated/api/client.py:55
msgid "Authorization error"
msgstr ""

#: nova/tests/integrated/api/client.py:63
msgid "Item not found"
msgstr ""

#: nova/tests/integrated/api/client.py:105
#, python-format
msgid "Doing %(method)s on %(relative_url)s"
msgstr ""

#: nova/tests/integrated/api/client.py:107
#, python-format
msgid "Body: %s"
msgstr ""

#: nova/tests/integrated/api/client.py:125
#, python-format
msgid "%(auth_uri)s => code %(http_status)s"
msgstr ""

#: nova/tests/integrated/api/client.py:151
#, python-format
msgid "%(relative_uri)s => code %(http_status)s"
msgstr ""

#: nova/tests/integrated/api/client.py:161
msgid "Unexpected status code"
msgstr ""

#: nova/tests/integrated/api/client.py:168
#, python-format
msgid "Decoding JSON: %s"
msgstr ""

#: nova/tests/rpc/common.py:131
#, python-format
msgid "Nested received %(queue)s, %(value)s"
msgstr "Nested received %(queue)s, %(value)s"

#: nova/tests/rpc/common.py:139
#, python-format
msgid "Nested return %s"
msgstr "Nested return %s"

#: nova/tests/rpc/common.py:157
msgid "RPC backend does not support timeouts"
msgstr ""

#: nova/tests/rpc/common.py:187 nova/tests/rpc/common.py:193
#, python-format
msgid "Received %s"
msgstr "Received %s"

#: nova/tests/scheduler/test_vsa_scheduler.py:147
#, python-format
msgid "Host %s"
msgstr ""

#: nova/tests/scheduler/test_vsa_scheduler.py:196
#, python-format
msgid "Test: provision vol %(name)s on host %(host)s"
msgstr ""

#: nova/tests/scheduler/test_vsa_scheduler.py:198
#, python-format
msgid "\t vol=%(vol)s"
msgstr ""

#: nova/tests/scheduler/test_vsa_scheduler.py:201
#, python-format
msgid "Test: VSA update request: vsa_id=%(vsa_id)s values=%(values)s"
msgstr ""

#: nova/tests/scheduler/test_vsa_scheduler.py:205
#, python-format
msgid "Test: Volume create: %s"
msgstr ""

#: nova/tests/scheduler/test_vsa_scheduler.py:212
#, python-format
msgid "Test: Volume get request: id=%(volume_id)s"
msgstr ""

#: nova/tests/scheduler/test_vsa_scheduler.py:219
#, python-format
msgid "Test: Volume update request: id=%(volume_id)s values=%(values)s"
msgstr ""

#: nova/tests/scheduler/test_vsa_scheduler.py:455
#, python-format
msgid "Test: Volume get: id=%(volume_id)s"
msgstr ""

#: nova/virt/connection.py:85
msgid "Failed to open connection to the hypervisor"
msgstr "Failed to open connection to the hypervisor"

#: nova/virt/fake.py:270 nova/virt/xenapi_conn.py:437
#: nova/virt/baremetal/proxy.py:716 nova/virt/libvirt/connection.py:1734
#, python-format
msgid "Compute_service record created for %s "
msgstr ""

#: nova/virt/fake.py:273 nova/virt/xenapi_conn.py:440
#: nova/virt/baremetal/proxy.py:720 nova/virt/libvirt/connection.py:1737
#, python-format
msgid "Compute_service record updated for %s "
msgstr ""

#: nova/virt/firewall.py:130
#, python-format
msgid "Attempted to unfilter instance %s which is not filtered"
msgstr "Attempted to unfilter instance %s which is not filtered"

#: nova/virt/firewall.py:137
#, python-format
msgid "Filters added to instance %s"
msgstr ""

#: nova/virt/firewall.py:139
msgid "Provider Firewall Rules refreshed"
msgstr ""

#: nova/virt/firewall.py:291
#, python-format
msgid "Adding security group rule: %r"
msgstr ""

#: nova/virt/firewall.py:402 nova/virt/xenapi/firewall.py:88
#, python-format
msgid "Adding provider rule: %s"
msgstr ""

#: nova/virt/images.py:95
msgid "'qemu-img info' parsing failed."
msgstr ""

#: nova/virt/images.py:101
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: nova/virt/images.py:114
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: nova/virt/vmwareapi_conn.py:105
msgid ""
"Must specify vmwareapi_host_ip,vmwareapi_host_username and "
"vmwareapi_host_password to useconnection_type=vmwareapi"
msgstr ""

#: nova/virt/vmwareapi_conn.py:276
#, python-format
msgid "In vmwareapi:_create_session, got this exception: %s"
msgstr ""

#: nova/virt/vmwareapi_conn.py:359
#, python-format
msgid "In vmwareapi:_call_method, got this exception: %s"
msgstr ""

#: nova/virt/vmwareapi_conn.py:398
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: success"
msgstr ""

#: nova/virt/vmwareapi_conn.py:404
#, python-format
msgid "Task [%(task_name)s] %(task_ref)s status: error %(error_info)s"
msgstr ""

#: nova/virt/vmwareapi_conn.py:409
#, python-format
msgid "In vmwareapi:_poll_task, Got this error %s"
msgstr ""

#: nova/virt/xenapi_conn.py:163
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username "
"(optionally), and xenapi_connection_password to use "
"connection_type=xenapi"
msgstr ""
"Must specify xenapi_connection_url, xenapi_connection_username "
"(optionally), and xenapi_connection_password to use "
"connection_type=xenapi"

#: nova/virt/xenapi_conn.py:371 nova/virt/libvirt/connection.py:441
msgid "Could not determine iscsi initiator name"
msgstr ""

#: nova/virt/xenapi_conn.py:501
msgid "Host startup on XenServer is not supported."
msgstr ""

#: nova/virt/xenapi_conn.py:530
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: nova/virt/xenapi_conn.py:556
msgid "Host is member of a pool, but DB says otherwise"
msgstr ""

#: nova/virt/xenapi_conn.py:648
#, python-format
msgid "Task [%(name)s] %(task)s status: success    %(result)s"
msgstr "Task [%(name)s] %(task)s status: success    %(result)s"

#: nova/virt/xenapi_conn.py:657
#, python-format
msgid "Task [%(name)s] %(task)s status: %(status)s    %(error_info)s"
msgstr "Task [%(name)s] %(task)s status: %(status)s    %(error_info)s"

#: nova/virt/xenapi_conn.py:677 nova/virt/xenapi_conn.py:690
#, python-format
msgid "Got exception: %s"
msgstr "Got exception: %s"

#: nova/virt/baremetal/dom.py:93
msgid "No domains exist."
msgstr ""

#: nova/virt/baremetal/dom.py:95
#, python-format
msgid "============= initial domains =========== : %s"
msgstr ""

#: nova/virt/baremetal/dom.py:99
msgid "Building domain: to be removed"
msgstr ""

#: nova/virt/baremetal/dom.py:103
msgid "Not running domain: remove"
msgstr ""

#: nova/virt/baremetal/dom.py:111
msgid "domain running on an unknown node: discarded"
msgstr ""

#: nova/virt/baremetal/dom.py:127
#, python-format
msgid "No such domain (%s)"
msgstr ""

#: nova/virt/baremetal/dom.py:134
#, python-format
msgid "Failed power down Bare-metal node %s"
msgstr ""

#: nova/virt/baremetal/dom.py:143
msgid "deactivate -> activate fails"
msgstr ""

#: nova/virt/baremetal/dom.py:153
msgid "destroy_domain: no such domain"
msgstr ""

#: nova/virt/baremetal/dom.py:154
#, python-format
msgid "No such domain %s"
msgstr ""

#: nova/virt/baremetal/dom.py:161
#, python-format
msgid "Domains: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:163
#, python-format
msgid "Nodes: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:166
#, python-format
msgid "After storing domains: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:169
msgid "deactivation/removing domain failed"
msgstr ""

#: nova/virt/baremetal/dom.py:176
msgid "===== Domain is being created ====="
msgstr ""

#: nova/virt/baremetal/dom.py:179
msgid "Same domain name already exists"
msgstr ""

#: nova/virt/baremetal/dom.py:181
msgid "create_domain: before get_idle_node"
msgstr ""

#: nova/virt/baremetal/dom.py:198
#, python-format
msgid "Created new domain: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:213
#, python-format
msgid "Failed to boot Bare-metal node %s"
msgstr ""

#: nova/virt/baremetal/dom.py:222
msgid "No such domain exists"
msgstr ""

#: nova/virt/baremetal/dom.py:226
#, python-format
msgid "change_domain_state: to new state %s"
msgstr ""

#: nova/virt/baremetal/dom.py:233
#, python-format
msgid "Stored fake domains to the file: %s"
msgstr ""

#: nova/virt/baremetal/dom.py:244
msgid "domain does not exist"
msgstr ""

#: nova/virt/baremetal/nodes.py:42
#, python-format
msgid "Unknown baremetal driver %(d)s"
msgstr ""

#: nova/virt/baremetal/proxy.py:148
#, python-format
msgid "Error encountered when destroying instance '%(name)s': %(ex)s"
msgstr ""

#: nova/virt/baremetal/proxy.py:162
#, python-format
msgid "instance %(instance_name)s: deleting instance files %(target)s"
msgstr "instance %(instance_name)s: deleting instance files %(target)s"

#: nova/virt/baremetal/proxy.py:189
#, python-format
msgid "instance %s: rebooted"
msgstr "instance %s: rebooted"

#: nova/virt/baremetal/proxy.py:192
msgid "_wait_for_reboot failed"
msgstr ""

#: nova/virt/baremetal/proxy.py:222
#, python-format
msgid "instance %s: rescued"
msgstr "instance %s: rescued"

#: nova/virt/baremetal/proxy.py:225
msgid "_wait_for_rescue failed"
msgstr ""

#: nova/virt/baremetal/proxy.py:242
msgid "<============= spawn of baremetal =============>"
msgstr ""

#: nova/virt/baremetal/proxy.py:255
#, python-format
msgid "instance %s: is building"
msgstr ""

#: nova/virt/baremetal/proxy.py:260
msgid "Key is injected but instance is not running yet"
msgstr ""

#: nova/virt/baremetal/proxy.py:265
#, python-format
msgid "instance %s: booted"
msgstr "instance %s: booted"

#: nova/virt/baremetal/proxy.py:268
#, python-format
msgid "~~~~~~ current state = %s ~~~~~~"
msgstr ""

#: nova/virt/baremetal/proxy.py:269
#, python-format
msgid "instance %s spawned successfully"
msgstr ""

#: nova/virt/baremetal/proxy.py:272
#, python-format
msgid "instance %s:not booted"
msgstr ""

#: nova/virt/baremetal/proxy.py:274
msgid "Bremetal assignment is overcommitted."
msgstr ""

#: nova/virt/baremetal/proxy.py:354
#, python-format
msgid "instance %s: Creating image"
msgstr "instance %s: Creating image"

#: nova/virt/baremetal/proxy.py:475
#, python-format
msgid "instance %(inst_name)s: injecting %(injection)s into image %(img_id)s"
msgstr ""

#: nova/virt/baremetal/proxy.py:484
#, python-format
msgid ""
"instance %(inst_name)s: ignoring error injecting data into image "
"%(img_id)s (%(e)s)"
msgstr ""
"instance %(inst_name)s: ignoring error injecting data into image "
"%(img_id)s (%(e)s)"

#: nova/virt/baremetal/proxy.py:529
#, python-format
msgid "instance %s: starting toXML method"
msgstr "instance %s: starting toXML method"

#: nova/virt/baremetal/proxy.py:531
#, python-format
msgid "instance %s: finished toXML method"
msgstr "instance %s: finished toXML method"

#: nova/virt/baremetal/proxy.py:574 nova/virt/libvirt/connection.py:1504
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. This error can be safely ignored for now."
msgstr ""

#: nova/virt/baremetal/proxy.py:714
#, python-format
msgid "#### RLK: cpu_arch = %s "
msgstr ""

#: nova/virt/baremetal/proxy.py:746
msgid "Updating!"
msgstr ""

#: nova/virt/baremetal/proxy.py:773 nova/virt/libvirt/connection.py:2281
#: nova/virt/xenapi/host.py:124
msgid "Updating host stats"
msgstr ""

#: nova/virt/baremetal/tilera.py:185
msgid "free_node...."
msgstr ""

#: nova/virt/baremetal/tilera.py:216
#, python-format
msgid "deactivate_node is called for node_id = %(id)s node_ip = %(ip)s"
msgstr ""

#: nova/virt/baremetal/tilera.py:221
msgid "status of node is set to 0"
msgstr ""

#: nova/virt/baremetal/tilera.py:232
msgid "rootfs is already removed"
msgstr ""

#: nova/virt/baremetal/tilera.py:264
msgid "Before ping to the bare-metal node"
msgstr ""

#: nova/virt/baremetal/tilera.py:317
msgid "activate_node"
msgstr ""

#: nova/virt/baremetal/tilera.py:331
msgid "Node is unknown error state."
msgstr ""

#: nova/virt/disk/api.py:152
msgid "no capable image handler configured"
msgstr ""

#: nova/virt/disk/api.py:165
#, python-format
msgid "unknown disk image handler: %s"
msgstr ""

#: nova/virt/disk/api.py:176
msgid "image already mounted"
msgstr ""

#: nova/virt/disk/api.py:263 nova/virt/disk/guestfs.py:64
#: nova/virt/disk/guestfs.py:78 nova/virt/disk/mount.py:100
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr "Failed to mount filesystem: %s"

#: nova/virt/disk/api.py:278
#, python-format
msgid "Failed to remove container: %s"
msgstr ""

#: nova/virt/disk/api.py:428
#, python-format
msgid "User %(username)s not found in password file."
msgstr ""

#: nova/virt/disk/api.py:444
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr ""

#: nova/virt/disk/guestfs.py:39
#, python-format
msgid "unsupported partition: %s"
msgstr ""

#: nova/virt/disk/guestfs.py:77
msgid "unknown guestmount error"
msgstr ""

#: nova/virt/disk/loop.py:30
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr "Could not attach image to loopback: %s"

#: nova/virt/disk/mount.py:76
msgid "no partitions found"
msgstr ""

#: nova/virt/disk/mount.py:77
#, python-format
msgid "Failed to map partitions: %s"
msgstr ""

#: nova/virt/disk/nbd.py:58
msgid "nbd unavailable: module not loaded"
msgstr ""

#: nova/virt/disk/nbd.py:63
msgid "No free nbd devices"
msgstr "No free nbd devices"

#: nova/virt/disk/nbd.py:81
#, python-format
msgid "qemu-nbd error: %s"
msgstr ""

#: nova/virt/disk/nbd.py:93
#, python-format
msgid "nbd device %s did not show up"
msgstr "nbd device %s did not show up"

#: nova/virt/libvirt/connection.py:248
#, python-format
msgid "Connecting to libvirt: %s"
msgstr "Connecting to libvirt: %s"

#: nova/virt/libvirt/connection.py:262
msgid "Connection to libvirt broke"
msgstr "Connection to libvirt broke"

#: nova/virt/libvirt/connection.py:364
#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/connection.py:376
#, python-format
msgid ""
"Error from libvirt during saved instance removal. Code=%(errcode)s "
"Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/connection.py:387
#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/connection.py:399
msgid "Instance destroyed successfully."
msgstr ""

#: nova/virt/libvirt/connection.py:430
#, python-format
msgid "Deleting instance files %(target)s"
msgstr ""

#: nova/virt/libvirt/connection.py:512
msgid "attaching LXC block device"
msgstr ""

#: nova/virt/libvirt/connection.py:525
msgid "detaching LXC block device"
msgstr ""

#: nova/virt/libvirt/connection.py:674 nova/virt/libvirt/connection.py:816
msgid "During reboot, instance disappeared."
msgstr ""

#: nova/virt/libvirt/connection.py:679
msgid "Instance rebooted successfully."
msgstr ""

#: nova/virt/libvirt/connection.py:776 nova/virt/xenapi/vmops.py:1372
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: nova/virt/libvirt/connection.py:780 nova/virt/xenapi/vmops.py:1376
#, python-format
msgid "Automatically confirming migration %d"
msgstr ""

#: nova/virt/libvirt/connection.py:807
msgid "Instance is running"
msgstr ""

#: nova/virt/libvirt/connection.py:821
msgid "Instance spawned successfully."
msgstr ""

#: nova/virt/libvirt/connection.py:829
#, python-format
msgid "virsh said: %r"
msgstr "virsh said: %r"

#: nova/virt/libvirt/connection.py:833
msgid "cool, it's a device"
msgstr "cool, it's a device"

#: nova/virt/libvirt/connection.py:844
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr "data: %(data)r, fpath: %(fpath)r"

#: nova/virt/libvirt/connection.py:871
msgid "Unable to read LXC console"
msgstr ""

#: nova/virt/libvirt/connection.py:994
msgid "Creating image"
msgstr ""

#: nova/virt/libvirt/connection.py:1181
#, python-format
msgid "Injecting %(injection)s into image %(img_id)s"
msgstr ""

#: nova/virt/libvirt/connection.py:1190
#, python-format
msgid "Ignoring error injecting data into image %(img_id)s (%(e)s)"
msgstr ""

#: nova/virt/libvirt/connection.py:1222
#, python-format
msgid "block_device_list %s"
msgstr ""

#: nova/virt/libvirt/connection.py:1347
msgid "Starting toXML method"
msgstr ""

#: nova/virt/libvirt/connection.py:1351
msgid "Finished toXML method"
msgstr ""

#: nova/virt/libvirt/connection.py:1368
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/connection.py:1609
msgid "libvirt version is too old (does not support getVersion)"
msgstr ""

#: nova/virt/libvirt/connection.py:1631
#, python-format
msgid "'<cpu>' must be 1, but %d\n"
msgstr ""

#: nova/virt/libvirt/connection.py:1658
#, python-format
msgid "topology (%(topology)s) must have %(ks)s"
msgstr ""

#: nova/virt/libvirt/connection.py:1755
#, python-format
msgid ""
"Instance launched has CPU info:\n"
"%s"
msgstr ""

#: nova/virt/libvirt/connection.py:1758
#, python-format
msgid ""
"to xml...\n"
":%s "
msgstr ""

#: nova/virt/libvirt/connection.py:1761
#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""

#: nova/virt/libvirt/connection.py:1818
#, python-format
msgid "Timeout migrating for %s. nwfilter not found."
msgstr ""

#: nova/virt/libvirt/connection.py:2033
#, python-format
msgid "skipping %(path)s since it looks like volume"
msgstr ""

#: nova/virt/libvirt/connection.py:2129
#, python-format
msgid "Instance %s: Starting migrate_disk_and_power_off"
msgstr ""

#: nova/virt/libvirt/connection.py:2184
msgid "During wait running, instance disappeared."
msgstr ""

#: nova/virt/libvirt/connection.py:2189
msgid "Instance running successfully."
msgstr ""

#: nova/virt/libvirt/connection.py:2196
#, python-format
msgid "Instance %s: Starting finish_migration"
msgstr ""

#: nova/virt/libvirt/connection.py:2237
#, python-format
msgid "Instance %s: Starting finish_revert_migration"
msgstr ""

#: nova/virt/libvirt/firewall.py:42
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: nova/virt/libvirt/firewall.py:93
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: nova/virt/libvirt/firewall.py:101
msgid "Ensuring static filters"
msgstr ""

#: nova/virt/libvirt/firewall.py:160
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) is not found."
msgstr ""

#: nova/virt/libvirt/firewall.py:206
#, python-format
msgid "The nwfilter(%(instance_filter_name)s) for%(name)s is not found."
msgstr ""

#: nova/virt/libvirt/firewall.py:222
msgid "iptables firewall: Setup Basic Filtering"
msgstr ""

#: nova/virt/libvirt/firewall.py:241
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: nova/virt/libvirt/imagecache.py:171
#, python-format
msgid "%s is a valid instance name"
msgstr ""

#: nova/virt/libvirt/imagecache.py:174
#, python-format
msgid "%s has a disk file"
msgstr ""

#: nova/virt/libvirt/imagecache.py:176
#, python-format
msgid "Instance %(instance)s is backed by %(backing)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:187
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: nova/virt/libvirt/imagecache.py:238
#, python-format
msgid "%(container_format)s-%(id)s (%(base_file)s): image verification failed"
msgstr ""

#: nova/virt/libvirt/imagecache.py:250
#, python-format
msgid ""
"%(container_format)s-%(id)s (%(base_file)s): image verification skipped, "
"no hash stored"
msgstr ""

#: nova/virt/libvirt/imagecache.py:270
#, python-format
msgid "Cannot remove %(base_file)s, it does not exist"
msgstr ""

#: nova/virt/libvirt/imagecache.py:282
#, python-format
msgid "Base file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:285
#, python-format
msgid "Removing base file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:292
#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:303
#, python-format
msgid "%(container_format)s-%(id)s (%(base_file)s): checking"
msgstr ""

#: nova/virt/libvirt/imagecache.py:320
#, python-format
msgid ""
"%(container_format)s-%(id)s (%(base_file)s): in use: on this node "
"%(local)d local, %(remote)d on other nodes"
msgstr ""

#: nova/virt/libvirt/imagecache.py:333
#, python-format
msgid ""
"%(container_format)s-%(id)s (%(base_file)s): warning -- an absent base "
"file is in use! instances: %(instance_list)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:344
#, python-format
msgid ""
"%(container_format)s-%(id)s (%(base_file)s): in use on (%(remote)d on "
"other nodes)"
msgstr ""

#: nova/virt/libvirt/imagecache.py:355
#, python-format
msgid "%(container_format)s-%(id)s (%(base_file)s): image is not in use"
msgstr ""

#: nova/virt/libvirt/imagecache.py:363
#, python-format
msgid "%(container_format)s-%(id)s (%(base_file)s): image is in use"
msgstr ""

#: nova/virt/libvirt/imagecache.py:387
#, python-format
msgid "Skipping verification, no base directory at %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:391
msgid "Verify base images"
msgstr ""

#: nova/virt/libvirt/imagecache.py:419
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:424
#, python-format
msgid "Active base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:427
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:431
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:439
msgid "Verification complete"
msgstr ""

#: nova/virt/libvirt/utils.py:240
msgid "Unable to find an open port"
msgstr "Unable to find an open port"

#: nova/virt/libvirt/vif.py:85
#, python-format
msgid "Ensuring vlan %(vlan)s and bridge %(bridge)s"
msgstr ""

#: nova/virt/libvirt/vif.py:93
#, python-format
msgid "Ensuring bridge %s"
msgstr ""

#: nova/virt/libvirt/vif.py:156
#, python-format
msgid "Failed while unplugging vif of instance '%s'"
msgstr ""

#: nova/virt/libvirt/volume.py:153 nova/volume/driver.py:817
#, python-format
msgid "iSCSI device not found at %s"
msgstr ""

#: nova/virt/libvirt/volume.py:156 nova/volume/driver.py:820
#, python-format
msgid ""
"ISCSI volume not yet found at: %(mount_device)s. Will rescan & retry.  "
"Try number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:168 nova/volume/driver.py:832
#, python-format
msgid "Found iSCSI node %(mount_device)s (after %(tries)s rescans)"
msgstr ""

#: nova/virt/vmwareapi/error_util.py:93
#, python-format
msgid "Error(s) %s occurred in the call to RetrieveProperties"
msgstr ""

#: nova/virt/vmwareapi/fake.py:44 nova/virt/xenapi/fake.py:77
#, python-format
msgid "%(text)s: _db_content => %(content)s"
msgstr "%(text)s: _db_content => %(content)s"

#: nova/virt/vmwareapi/fake.py:131
#, python-format
msgid "Property %(attr)s not set for the managed object %(objName)s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:437
msgid "There is no VM registered"
msgstr ""

#: nova/virt/vmwareapi/fake.py:439 nova/virt/vmwareapi/fake.py:609
#, python-format
msgid "Virtual Machine with ref %s is not there"
msgstr ""

#: nova/virt/vmwareapi/fake.py:502
#, python-format
msgid "Logging out a session that is invalid or already logged out: %s"
msgstr ""

#: nova/virt/vmwareapi/fake.py:517
msgid "Session is faulty"
msgstr ""

#: nova/virt/vmwareapi/fake.py:520
msgid "Session Invalid"
msgstr ""

#: nova/virt/vmwareapi/fake.py:606
msgid " No Virtual Machine has been registered yet"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:99
#, python-format
msgid "Glance image %s is in killed state"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:107
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:128
msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:155
#, python-format
msgid "Creating Port Group with name %s on the ESX host"
msgstr ""

#: nova/virt/vmwareapi/network_utils.py:169
#, python-format
msgid "Created Port Group with name %s on the ESX host"
msgstr ""

#: nova/virt/vmwareapi/read_write_util.py:150
#, python-format
msgid "Exception during HTTP connection close in VMWareHTTpWrite. Exception is %s"
msgstr ""

#: nova/virt/vmwareapi/vim.py:84
msgid "Unable to import suds."
msgstr ""

#: nova/virt/vmwareapi/vim.py:90
msgid "Must specify vmwareapi_wsdl_loc"
msgstr ""

#: nova/virt/vmwareapi/vim.py:145
#, python-format
msgid "No such SOAP method '%s' provided by VI SDK"
msgstr ""

#: nova/virt/vmwareapi/vim.py:150
#, python-format
msgid "httplib error in %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:157
#, python-format
msgid "Socket error in %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:162
#, python-format
msgid "Type error in  %s: "
msgstr ""

#: nova/virt/vmwareapi/vim.py:166
#, python-format
msgid "Exception in %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:66
msgid "Getting list of instances"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:82
#, python-format
msgid "Got total of %s instances"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:125
msgid "Couldn't get a local Datastore reference"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:195
#, python-format
msgid "Creating VM with the name %s on the ESX  host"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:204
#, python-format
msgid "Created VM with the name %s on the ESX  host"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:233
#, python-format
msgid ""
"Creating Virtual Disk of size  %(vmdk_file_size_in_kb)s KB and adapter "
"type  %(adapter_type)s on the ESX host local store %(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:250
#, python-format
msgid ""
"Created Virtual Disk of size %(vmdk_file_size_in_kb)s KB on the ESX host "
"local store %(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:259
#, python-format
msgid ""
"Deleting the file %(flat_uploaded_vmdk_path)s on the ESX host localstore "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:271
#, python-format
msgid ""
"Deleted the file %(flat_uploaded_vmdk_path)s on the ESX host local store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:282
#, python-format
msgid ""
"Downloading image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:297
#, python-format
msgid ""
"Downloaded image file data %(image_ref)s to the ESX data store "
"%(data_store_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:314
#, python-format
msgid "Reconfiguring VM instance %s to attach the image disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:321
#, python-format
msgid "Reconfigured VM instance %s to attach the image disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:328
#, python-format
msgid "Powering on the VM instance %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:334
#, python-format
msgid "Powered on the VM instance %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:379
#, python-format
msgid "Creating Snapshot of the VM instance %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:389
#, python-format
msgid "Created Snapshot of the VM instance %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:432
#, python-format
msgid "Copying disk data before snapshot of the VM  instance %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:445
#, python-format
msgid "Copied disk data before snapshot of the VM instance %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:454
#, python-format
msgid "Uploading image %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:467
#, python-format
msgid "Uploaded image %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:477
#, python-format
msgid "Deleting temporary vmdk file %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:486
#, python-format
msgid "Deleted temporary vmdk file %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:518
msgid "instance is not powered on"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:525
#, python-format
msgid "Rebooting guest OS of VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:528
#, python-format
msgid "Rebooted guest OS of VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:530
#, python-format
msgid "Doing hard reboot of VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:534
#, python-format
msgid "Did hard reboot of VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:546
#, python-format
msgid "instance - %s not present"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:565
#, python-format
msgid "Powering off the VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:570
#, python-format
msgid "Powered off the VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:574
#, python-format
msgid "Unregistering the VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:577
#, python-format
msgid "Unregistered the VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:579
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while un-registering the "
"VM: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:590
#, python-format
msgid "Deleting contents of the VM %(name)s from datastore %(datastore_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:600
#, python-format
msgid "Deleted contents of the VM %(name)s from datastore %(datastore_name)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:605
#, python-format
msgid ""
"In vmwareapi:vmops:destroy, got this exception while deleting the VM "
"contents from the disk: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:613
msgid "pause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:617
msgid "unpause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:631
#, python-format
msgid "Suspending the VM %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:635
#, python-format
msgid "Suspended the VM %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:638
msgid "instance is powered off and can not be suspended."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:641
#, python-format
msgid "VM %s was already in suspended state. So returning without doing anything"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:654
#, python-format
msgid "Resuming the VM %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:659
#, python-format
msgid "Resumed the VM %s "
msgstr ""

#: nova/virt/vmwareapi/vmops.py:661
msgid "instance is not in a suspended state"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:697
msgid "get_diagnostics not implemented for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:755
#, python-format
msgid ""
"Reconfiguring VM instance %(name)s to set the machine id with ip - "
"%(ip_addr)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:763
#, python-format
msgid ""
"Reconfigured VM instance %(name)s to set the machine id with ip - "
"%(ip_addr)s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:800
#, python-format
msgid "Creating directory with path %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:804
#, python-format
msgid "Created directory with path %s"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:89
#, python-format
msgid "Downloading image %s from glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:103
#, python-format
msgid "Downloaded image %s from glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:108
#, python-format
msgid "Uploading image %s to the Glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:129
#, python-format
msgid "Uploaded image %s to the Glance image server"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:139
#, python-format
msgid "Getting image size for the image %s"
msgstr ""

#: nova/virt/vmwareapi/vmware_images.py:143
#, python-format
msgid "Got image size of %(size)s for the image %(image)s"
msgstr ""

#: nova/virt/xenapi/fake.py:555 nova/virt/xenapi/fake.py:654
#: nova/virt/xenapi/fake.py:672 nova/virt/xenapi/fake.py:734
msgid "Raising NotImplemented"
msgstr "Raising NotImplemented"

#: nova/virt/xenapi/fake.py:557
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr "xenapi.fake does not have an implementation for %s"

#: nova/virt/xenapi/fake.py:591
#, python-format
msgid "Calling %(localname)s %(impl)s"
msgstr "Calling %(localname)s %(impl)s"

#: nova/virt/xenapi/fake.py:596
#, python-format
msgid "Calling getter %s"
msgstr "Calling getter %s"

#: nova/virt/xenapi/fake.py:656
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"

#: nova/virt/xenapi/host.py:67
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skipping migration to a new host"
msgstr ""

#: nova/virt/xenapi/host.py:132
#, python-format
msgid "Unable to get SR for this host: %s"
msgstr ""

#: nova/virt/xenapi/host.py:166
msgid "Unable to get updated status"
msgstr ""

#: nova/virt/xenapi/host.py:169
#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr ""

#: nova/virt/xenapi/network_utils.py:37
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:55
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr "Found non-unique network for bridge %s"

#: nova/virt/xenapi/network_utils.py:58
#, python-format
msgid "Found no network for bridge %s"
msgstr "Found no network for bridge %s"

#: nova/virt/xenapi/pool.py:111
#, python-format
msgid "Unable to eject %(host)s from the pool; pool not empty"
msgstr ""

#: nova/virt/xenapi/pool.py:126
#, python-format
msgid "Unable to eject %(host)s from the pool; No master found"
msgstr ""

#: nova/virt/xenapi/pool.py:145
#, python-format
msgid "Pool-Join failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/pool.py:148
#, python-format
msgid "Unable to join %(host)s in the pool"
msgstr ""

#: nova/virt/xenapi/pool.py:164
#, python-format
msgid "Pool-eject failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/pool.py:176
#, fuzzy, python-format
msgid "Unable to set up pool: %(e)s."
msgstr "Unable to detach volume %s"

#: nova/virt/xenapi/pool.py:187
#, python-format
msgid "Pool-set_name_label failed: %(e)s"
msgstr ""

#: nova/virt/xenapi/vif.py:103
#, python-format
msgid "Found no PIF for device %s"
msgstr ""

#: nova/virt/xenapi/vif.py:122
#, python-format
msgid ""
"PIF %(pif_rec['uuid'])s for network %(bridge)s has VLAN id %(pif_vlan)d. "
"Expected %(vlan_num)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:215
#, python-format
msgid "Created VM %s..."
msgstr "Created VM %s..."

#: nova/virt/xenapi/vm_utils.py:218
#, python-format
msgid "Created VM %(instance_name)s as %(vm_ref)s."
msgstr "Created VM %(instance_name)s as %(vm_ref)s."

#: nova/virt/xenapi/vm_utils.py:249
#, python-format
msgid "Creating a CDROM-specific VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:252
#, python-format
msgid ""
"Created a CDROM-specific VBD %(vbd_ref)s  for VM %(vm_ref)s, VDI "
"%(vdi_ref)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:269
#, python-format
msgid "VBD not found in instance %s"
msgstr "VBD not found in instance %s"

#: nova/virt/xenapi/vm_utils.py:280
#, python-format
msgid "Unable to unplug VBD %s"
msgstr "Unable to unplug VBD %s"

#: nova/virt/xenapi/vm_utils.py:291
#, python-format
msgid "Unable to destroy VBD %s"
msgstr "Unable to destroy VBD %s"

#: nova/virt/xenapi/vm_utils.py:301
#, python-format
msgid "Unable to destroy VDI %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:318
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s)"
" on %(sr_ref)s."
msgstr ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s)"
" on %(sr_ref)s."

#: nova/virt/xenapi/vm_utils.py:327
#, python-format
msgid "Copied VDI %(vdi_ref)s from VDI %(vdi_to_copy_ref)s on %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:335
#, python-format
msgid "Cloned VDI %(vdi_ref)s from VDI %(vdi_to_clone_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:354
#, python-format
msgid "No primary VDI found for%(vm_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:361
#, python-format
msgid "Snapshotting VM %(vm_ref)s with label '%(label)s'..."
msgstr "Snapshotting VM %(vm_ref)s with label '%(label)s'..."

#: nova/virt/xenapi/vm_utils.py:375
#, python-format
msgid "Created snapshot %(template_vm_ref)s from VM %(vm_ref)s."
msgstr "Created snapshot %(template_vm_ref)s from VM %(vm_ref)s."

#: nova/virt/xenapi/vm_utils.py:414
#, python-format
msgid "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"
msgstr "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"

#: nova/virt/xenapi/vm_utils.py:624
#, python-format
msgid ""
"Fast cloning is only supported on default local SR of type ext. SR on "
"this system was found to be of type %(sr_type)s. Ignoring the cow flag."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:703
#, python-format
msgid "Asking xapi to fetch vhd image %(image)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:731
#, python-format
msgid ""
"xapi 'download_vhd' returned VDI of type '%(vdi_type)s' with UUID "
"'%(vdi_uuid)s'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:760
#, python-format
msgid "vdi_uuid=%(cur_vdi_uuid)s vdi_size_bytes=%(vdi_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:775
#, python-format
msgid "image_size_bytes=%(size_bytes)d, allowed_size_bytes=%(allowed_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:779
#, python-format
msgid ""
"Image size %(size_bytes)d exceeded instance_type allowed size "
"%(allowed_size_bytes)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:802
#, python-format
msgid "Fetching image %(image)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:803
#, python-format
msgid "Image Type: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:807
msgid "ISO: Found sr possibly containing the ISO image"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:816
#, python-format
msgid "Size for image %(image)s:%(virtual_size)d"
msgstr "Size for image %(image)s:%(virtual_size)d"

#: nova/virt/xenapi/vm_utils.py:825
#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:842
#, python-format
msgid "Copying VDI %s to /boot/guest on dom0"
msgstr "Copying VDI %s to /boot/guest on dom0"

#: nova/virt/xenapi/vm_utils.py:854
#, python-format
msgid "Kernel/Ramdisk VDI %s destroyed"
msgstr "Kernel/Ramdisk VDI %s destroyed"

#: nova/virt/xenapi/vm_utils.py:864
#, python-format
msgid "instance %s: Failed to fetch glance image"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:903
#, python-format
msgid "Detected %(image_type_str)s format for image %(image_ref)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:925
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr "Looking up vdi %s for PV kernel"

#: nova/virt/xenapi/vm_utils.py:943
#, python-format
msgid "Unknown image format %(disk_image_type)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:986
#, python-format
msgid "VDI %s is still available"
msgstr "VDI %s is still available"

#: nova/virt/xenapi/vm_utils.py:1032
#, python-format
msgid "(VM_UTILS) xenserver vm state -> |%s|"
msgstr "(VM_UTILS) xenserver vm state -> |%s|"

#: nova/virt/xenapi/vm_utils.py:1034
#, python-format
msgid "(VM_UTILS) xenapi power_state -> |%s|"
msgstr "(VM_UTILS) xenapi power_state -> |%s|"

#: nova/virt/xenapi/vm_utils.py:1061
#, python-format
msgid "Unable to parse rrd of %(vm_uuid)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1081
#, python-format
msgid "Re-scanning SR %s"
msgstr "Re-scanning SR %s"

#: nova/virt/xenapi/vm_utils.py:1112
#, python-format
msgid "Flag sr_matching_filter '%s' does not respect formatting convention"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1130
msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances "
"on. Please check your configuration and/or configure the flag "
"'sr_matching_filter'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1143
msgid "Cannot find SR of content-type ISO"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1151
#, python-format
msgid "ISO: looking at SR %(sr_rec)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1153
msgid "ISO: not iso content"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1156
msgid "ISO: iso content_type, no 'i18n-key' key"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1159
msgid "ISO: iso content_type, i18n-key value not 'local-storage-iso'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1163
msgid "ISO: SR MATCHing our criteria"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1165
msgid "ISO: ISO, looking to see if it is host local"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1168
#, python-format
msgid "ISO: PBD %(pbd_ref)s disappeared"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1171
#, python-format
msgid "ISO: PBD matching, want %(pbd_rec)s, have %(host)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1174
msgid "ISO: SR with local PBD"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1196
#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: "
"%(server)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1212
#, python-format
msgid "Unable to obtain RRD XML updates with server details: %(server)s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1266
#, python-format
msgid "Invalid statistics data from Xenserver: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1319
#, python-format
msgid "VHD %(vdi_uuid)s has parent %(parent_ref)s"
msgstr "VHD %(vdi_uuid)s has parent %(parent_ref)s"

#: nova/virt/xenapi/vm_utils.py:1393
#, python-format
msgid ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."
msgstr ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."

#: nova/virt/xenapi/vm_utils.py:1403
#, python-format
msgid "VHD coalesce attempts exceeded (%(max_attempts)d), giving up..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1438
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1457
#, python-format
msgid "Creating VBD for VDI %s ... "
msgstr "Creating VBD for VDI %s ... "

#: nova/virt/xenapi/vm_utils.py:1459
#, python-format
msgid "Creating VBD for VDI %s done."
msgstr "Creating VBD for VDI %s done."

#: nova/virt/xenapi/vm_utils.py:1461
#, python-format
msgid "Plugging VBD %s ... "
msgstr "Plugging VBD %s ... "

#: nova/virt/xenapi/vm_utils.py:1464
#, python-format
msgid "Plugging VBD %s done."
msgstr "Plugging VBD %s done."

#: nova/virt/xenapi/vm_utils.py:1466
#, python-format
msgid "VBD %(vbd_ref)s plugged as %(orig_dev)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1469
#, python-format
msgid "VBD %(vbd_ref)s plugged into wrong dev, remapping to %(dev)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1478
#, python-format
msgid "Destroying VBD for VDI %s ... "
msgstr "Destroying VBD for VDI %s ... "

#: nova/virt/xenapi/vm_utils.py:1482
#, python-format
msgid "Destroying VBD for VDI %s done."
msgstr "Destroying VBD for VDI %s done."

#: nova/virt/xenapi/vm_utils.py:1493
msgid "VBD.unplug successful first time."
msgstr "VBD.unplug successful first time."

#: nova/virt/xenapi/vm_utils.py:1498
msgid "VBD.unplug rejected: retrying..."
msgstr "VBD.unplug rejected: retrying..."

#: nova/virt/xenapi/vm_utils.py:1500
msgid "Not sleeping anymore!"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1503
msgid "VBD.unplug successful eventually."
msgstr "VBD.unplug successful eventually."

#: nova/virt/xenapi/vm_utils.py:1506
#, python-format
msgid "Ignoring XenAPI.Failure in VBD.unplug: %s"
msgstr "Ignoring XenAPI.Failure in VBD.unplug: %s"

#: nova/virt/xenapi/vm_utils.py:1515
#, python-format
msgid "Ignoring XenAPI.Failure %s"
msgstr "Ignoring XenAPI.Failure %s"

#: nova/virt/xenapi/vm_utils.py:1529
#, python-format
msgid "Running pygrub against %s"
msgstr "Running pygrub against %s"

#: nova/virt/xenapi/vm_utils.py:1536
#, python-format
msgid "Found Xen kernel %s"
msgstr "Found Xen kernel %s"

#: nova/virt/xenapi/vm_utils.py:1538
msgid "No Xen kernel found.  Booting HVM."
msgstr "No Xen kernel found.  Booting HVM."

#: nova/virt/xenapi/vm_utils.py:1551
msgid "Partitions:"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1557
#, python-format
msgid "  %(num)s: %(ptype)s %(size)d sectors"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1583
#, python-format
msgid ""
"Writing partition table %(primary_first)d %(primary_last)d to "
"%(dev_path)s..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1596
#, python-format
msgid "Writing partition table %s done."
msgstr "Writing partition table %s done."

#: nova/virt/xenapi/vm_utils.py:1650
#, python-format
msgid ""
"Starting sparse_copy src=%(src_path)s dst=%(dst_path)s "
"virtual_size=%(virtual_size)d block_size=%(block_size)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1677
#, python-format
msgid ""
"Finished sparse_copy in %(duration).2f secs, %(compression_pct).2f%% "
"reduction in size"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1727
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1735
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1739
msgid "XenServer tools are not installed in this image"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1756
msgid "Manipulating interface files directly"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1766
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:181
#, python-format
msgid "Attempted to power on non-existent instance bad instance id %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:183
#, python-format
msgid "Starting instance %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:248
#, python-format
msgid "instance %s: Failed to spawn"
msgstr "instance %s: Failed to spawn"

#: nova/virt/xenapi/vmops.py:250
#, python-format
msgid "Instance %s failed to spawn - performing clean-up"
msgstr ""

#: nova/virt/xenapi/vmops.py:324
#, python-format
msgid "instance %s: Failed to spawn - Unable to create VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:391
#, python-format
msgid ""
"Auto configuring disk for instance %(instance_uuid)s, attempting to "
"resize partition..."
msgstr ""

#: nova/virt/xenapi/vmops.py:450
#, python-format
msgid "Invalid value for injected_files: '%s'"
msgstr ""

#: nova/virt/xenapi/vmops.py:455
#, python-format
msgid "Injecting file path: '%s'"
msgstr "Injecting file path: '%s'"

#: nova/virt/xenapi/vmops.py:461
msgid "Setting admin password"
msgstr ""

#: nova/virt/xenapi/vmops.py:465
msgid "Resetting network"
msgstr ""

#: nova/virt/xenapi/vmops.py:472
msgid "Setting VCPU weight"
msgstr ""

#: nova/virt/xenapi/vmops.py:478
#, python-format
msgid "Starting VM %s..."
msgstr "Starting VM %s..."

#: nova/virt/xenapi/vmops.py:481
#, python-format
msgid "Spawning VM %(instance_uuid)s created %(vm_ref)s."
msgstr ""

#: nova/virt/xenapi/vmops.py:488
#, python-format
msgid ""
"Latest agent build for %(hypervisor)s/%(os)s/%(architecture)s is "
"%(version)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:491
#, python-format
msgid "No agent build found for %(hypervisor)s/%(os)s/%(architecture)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:498
#, python-format
msgid "Instance %s: waiting for running"
msgstr ""

#: nova/virt/xenapi/vmops.py:507
#, python-format
msgid "Instance %s: running"
msgstr ""

#: nova/virt/xenapi/vmops.py:511
msgid "Querying agent version"
msgstr ""

#: nova/virt/xenapi/vmops.py:514
#, python-format
msgid "Instance agent version: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:518
#, python-format
msgid "Updating Agent to %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:540
#, python-format
msgid "Resources to remove:%s"
msgstr ""

#: nova/virt/xenapi/vmops.py:551
#, python-format
msgid "Removing VDI %(vdi_ref)s(uuid:%(vdi_to_remove)s)"
msgstr ""

#: nova/virt/xenapi/vmops.py:556
#, python-format
msgid "Skipping VDI destroy for %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:565
msgid "Removing kernel/ramdisk files from dom0"
msgstr ""

#: nova/virt/xenapi/vmops.py:594
#, python-format
msgid "No opaque_ref could be determined for '%s'."
msgstr ""

#: nova/virt/xenapi/vmops.py:648
#, python-format
msgid "Finished snapshot and upload for VM %s"
msgstr "Finished snapshot and upload for VM %s"

#: nova/virt/xenapi/vmops.py:656
#, python-format
msgid "Starting snapshot for VM %s"
msgstr "Starting snapshot for VM %s"

#: nova/virt/xenapi/vmops.py:665
#, python-format
msgid "Unable to Snapshot instance %(instance_uuid)s: %(exc)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:684
msgid "Failed to transfer vhd to new host"
msgstr ""

#: nova/virt/xenapi/vmops.py:704
#, python-format
msgid "Updating instance '%(instance_uuid)s' progress to %(progress)d"
msgstr ""

#: nova/virt/xenapi/vmops.py:752
#, python-format
msgid "Resizing down VDI %(cow_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: nova/virt/xenapi/vmops.py:875
#, python-format
msgid "Resizing up VDI %(vdi_uuid)s from %(old_gb)dGB to %(new_gb)dGB"
msgstr ""

#: nova/virt/xenapi/vmops.py:883
#, python-format
msgid "Resize instance %s complete"
msgstr ""

#: nova/virt/xenapi/vmops.py:914
#, python-format
msgid "Failed to query agent version: %(resp)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:934
#, python-format
msgid "domid changed from %(olddomid)s to %(newdomid)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:950
#, python-format
msgid "Failed to update agent: %(resp)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:973
#, python-format
msgid "Failed to exchange keys: %(resp)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:989
#, python-format
msgid "Failed to update password: %(resp)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:1016
#, python-format
msgid "Failed to inject file: %(resp)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:1025
#, python-format
msgid "VM %(instance_uuid)s already halted,skipping shutdown..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1029
#, python-format
msgid "Shutting down VM for Instance %(instance_uuid)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1048
msgid "Unable to find VBD for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:1069
#, python-format
msgid "Destroying VDIs for Instance %(instance_uuid)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1127
#, python-format
msgid ""
"Instance %(instance_uuid)s using RAW or VHD, skipping kernel and ramdisk "
"deletion"
msgstr ""

#: nova/virt/xenapi/vmops.py:1134
msgid "instance has a kernel or ramdisk but not both"
msgstr ""

#: nova/virt/xenapi/vmops.py:1141
msgid "kernel/ramdisk files removed"
msgstr "kernel/ramdisk files removed"

#: nova/virt/xenapi/vmops.py:1153
#, python-format
msgid "Instance %(instance_uuid)s VM destroyed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1171
#, python-format
msgid "Destroying VM for Instance %(instance_uuid)s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1186
msgid "VM is not present, skipping destroy..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1240
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1312
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: nova/virt/xenapi/vmops.py:1316
#, python-format
msgid "Automatically hard rebooting %d"
msgstr ""

#: nova/virt/xenapi/vmops.py:1381
#, python-format
msgid "Instance for migration %d not found, skipping"
msgstr ""

#: nova/virt/xenapi/vmops.py:1413
msgid "Could not get bandwidth info."
msgstr ""

#: nova/virt/xenapi/vmops.py:1464
#, python-format
msgid "injecting network info to xs for vm: |%s|"
msgstr ""

#: nova/virt/xenapi/vmops.py:1482
#, python-format
msgid "creating vif(s) for vm: |%s|"
msgstr ""

#: nova/virt/xenapi/vmops.py:1491
#, python-format
msgid "Creating VIF for VM %(vm_ref)s, network %(network_ref)s."
msgstr "Creating VIF for VM %(vm_ref)s, network %(network_ref)s."

#: nova/virt/xenapi/vmops.py:1494
#, python-format
msgid "Created VIF %(vif_ref)s for VM %(vm_ref)s, network %(network_ref)s."
msgstr "Created VIF %(vif_ref)s for VM %(vm_ref)s, network %(network_ref)s."

#: nova/virt/xenapi/vmops.py:1523
#, python-format
msgid "injecting hostname to xs for vm: |%s|"
msgstr ""

#: nova/virt/xenapi/vmops.py:1585
#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. VM "
"id=%(instance_uuid)s; path=%(path)s; args=%(addl_args)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:1610
#, python-format
msgid ""
"TIMEOUT: The call to %(method)s timed out. VM id=%(instance_uuid)s; "
"args=%(args)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:1614
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. VM"
" id=%(instance_uuid)s; args=%(args)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:1619
#, python-format
msgid ""
"The call to %(method)s returned an error: %(e)s. VM id=%(instance_uuid)s;"
" args=%(args)r"
msgstr ""

#: nova/virt/xenapi/vmops.py:1805
#, python-format
msgid "OpenSSL error: %s"
msgstr "OpenSSL error: %s"

#: nova/virt/xenapi/volume_utils.py:52
msgid "creating sr within volume_utils"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:55 nova/virt/xenapi/volume_utils.py:83
#, python-format
msgid "type is = %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:58 nova/virt/xenapi/volume_utils.py:86
#, python-format
msgid "name = %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:71
#, python-format
msgid "Created %(label)s as %(sr_ref)s."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:76 nova/virt/xenapi/volume_utils.py:174
msgid "Unable to create Storage Repository"
msgstr "Unable to create Storage Repository"

#: nova/virt/xenapi/volume_utils.py:80
msgid "introducing sr within volume_utils"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:103 nova/virt/xenapi/volume_utils.py:170
#: nova/virt/xenapi/volumeops.py:157
#, python-format
msgid "Introduced %(label)s as %(sr_ref)s."
msgstr "Introduced %(label)s as %(sr_ref)s."

#: nova/virt/xenapi/volume_utils.py:106
msgid "Creating pbd for SR"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:108
msgid "Plugging SR"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:116 nova/virt/xenapi/volumeops.py:160
msgid "Unable to introduce Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:127 nova/virt/xenapi/volumeops.py:51
msgid "Unable to get SR using uuid"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:129
#, python-format
msgid "Forgetting SR %s..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:137
msgid "Unable to forget Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:157
#, python-format
msgid "Introducing %s..."
msgstr "Introducing %s..."

#: nova/virt/xenapi/volume_utils.py:186
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr "Unable to find SR from VBD %s"

#: nova/virt/xenapi/volume_utils.py:206
#, python-format
msgid "Creating VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr "Creating VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "

#: nova/virt/xenapi/volume_utils.py:209
#, python-format
msgid "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."
msgstr "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."

#: nova/virt/xenapi/volume_utils.py:228
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"

#: nova/virt/xenapi/volume_utils.py:234
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"

#: nova/virt/xenapi/volume_utils.py:258
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr "Unable to introduce VDI on SR %s"

#: nova/virt/xenapi/volume_utils.py:266
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr "Unable to get record of VDI %s on"

#: nova/virt/xenapi/volume_utils.py:288
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr "Unable to introduce VDI for SR %s"

#: nova/virt/xenapi/volume_utils.py:298
#, python-format
msgid "Error finding vdis in SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:305
#, python-format
msgid "Unable to find vbd for vdi %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:339
#, python-format
msgid "Unable to obtain target information %(data)s, %(mountpoint)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:365
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr "Mountpoint cannot be translated: %s"

#: nova/virt/xenapi/volumeops.py:65
msgid "Could not find VDI ref"
msgstr ""

#: nova/virt/xenapi/volumeops.py:71
msgid "Error destroying VDI"
msgstr ""

#: nova/virt/xenapi/volumeops.py:74
#, python-format
msgid "Creating SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:77
msgid "Could not create SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:80
msgid "Could not retrieve SR record"
msgstr ""

#: nova/virt/xenapi/volumeops.py:85
#, python-format
msgid "Introducing SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:88
msgid "SR found in xapi database. No need to introduce"
msgstr ""

#: nova/virt/xenapi/volumeops.py:93
msgid "Could not introduce SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:97
#, python-format
msgid "Checking for SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:107
#, python-format
msgid "SR %s not found in the xapi database"
msgstr ""

#: nova/virt/xenapi/volumeops.py:113
msgid "Could not forget SR"
msgstr ""

#: nova/virt/xenapi/volumeops.py:122
#, python-format
msgid "Attach_volume: %(connection_info)s, %(instance_name)s, %(mountpoint)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:179
#, python-format
msgid "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"
msgstr "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"

#: nova/virt/xenapi/volumeops.py:192
#, python-format
msgid "Unable to use SR %(sr_ref)s for instance %(instance_name)s"
msgstr "Unable to use SR %(sr_ref)s for instance %(instance_name)s"

#: nova/virt/xenapi/volumeops.py:200
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "Unable to attach volume to instance %s"

#: nova/virt/xenapi/volumeops.py:203
#, python-format
msgid "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"
msgstr "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"

#: nova/virt/xenapi/volumeops.py:213
#, python-format
msgid "Detach_volume: %(instance_name)s, %(mountpoint)s"
msgstr "Detach_volume: %(instance_name)s, %(mountpoint)s"

#: nova/virt/xenapi/volumeops.py:221
#, python-format
msgid "Unable to locate volume %s"
msgstr "Unable to locate volume %s"

#: nova/virt/xenapi/volumeops.py:229
#, python-format
msgid "Unable to detach volume %s"
msgstr "Unable to detach volume %s"

#: nova/virt/xenapi/volumeops.py:234
#, python-format
msgid "Unable to destroy vbd %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:241
#, python-format
msgid "Error purging SR %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:243
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"

#: nova/vnc/xvp_proxy.py:98 nova/vnc/xvp_proxy.py:103
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:119
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:139
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:142
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:153
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:160
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:180
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/api.py:74 nova/volume/api.py:210
msgid "status must be available"
msgstr ""

#: nova/volume/api.py:85
#, python-format
msgid "Quota exceeded for %(pid)s, tried to create %(size)sG volume"
msgstr ""

#: nova/volume/api.py:133
msgid "Volume status must be available"
msgstr "Volume status must be available"

#: nova/volume/api.py:213
msgid "already attached"
msgstr ""

#: nova/volume/api.py:220
msgid "already detached"
msgstr ""

#: nova/volume/api.py:282 nova/volume/api.py:315
msgid "must be available"
msgstr ""

#: nova/volume/driver.py:92
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr "Recovering from a failed execute.  Try number %s"

#: nova/volume/driver.py:102
#, python-format
msgid "volume group %s doesn't exist"
msgstr "volume group %s doesn't exist"

#: nova/volume/driver.py:264 nova/volume/driver.py:866
#, python-format
msgid "Skipping ensure_export. No iscsi_target provisioned for volume: %d"
msgstr ""

#: nova/volume/driver.py:312 nova/volume/driver.py:910
#, python-format
msgid "Skipping remove_export. No iscsi_target provisioned for volume: %d"
msgstr ""

#: nova/volume/driver.py:321
#, python-format
msgid ""
"Skipping remove_export. No iscsi_target is presently exported for volume:"
" %d"
msgstr ""

#: nova/volume/driver.py:331
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: nova/volume/driver.py:378
#, python-format
msgid "Could not find iSCSI export  for volume %s"
msgstr "Could not find iSCSI export  for volume %s"

#: nova/volume/driver.py:382
#, python-format
msgid "ISCSI Discovery: Found %s"
msgstr ""

#: nova/volume/driver.py:459
#, python-format
msgid "Cannot confirm exported volume id:%(volume_id)s."
msgstr ""

#: nova/volume/driver.py:486
#, python-format
msgid "FAKE ISCSI: %s"
msgstr "FAKE ISCSI: %s"

#: nova/volume/driver.py:498
#, python-format
msgid "rbd has no pool %s"
msgstr "rbd has no pool %s"

#: nova/volume/driver.py:568
#, python-format
msgid "Sheepdog is not working: %s"
msgstr "Sheepdog is not working: %s"

#: nova/volume/driver.py:570
msgid "Sheepdog is not working"
msgstr "Sheepdog is not working"

#: nova/volume/driver.py:669 nova/volume/driver.py:674
#, python-format
msgid "LoggingVolumeDriver: %s"
msgstr ""

#: nova/volume/driver.py:709
#, python-format
msgid "\tVolume %s is NOT VSA volume"
msgstr ""

#: nova/volume/driver.py:725
#, python-format
msgid "\tFE VSA Volume %s creation - do nothing"
msgstr ""

#: nova/volume/driver.py:758
#, python-format
msgid "VSA BE create_volume for %s failed"
msgstr ""

#: nova/volume/driver.py:761
#, python-format
msgid "VSA BE create_volume for %s succeeded"
msgstr ""

#: nova/volume/driver.py:769
#, python-format
msgid "\tFE VSA Volume %s deletion - do nothing"
msgstr ""

#: nova/volume/driver.py:780
#, python-format
msgid "VSA BE delete_volume for %s failed"
msgstr ""

#: nova/volume/driver.py:783
#, python-format
msgid "VSA BE delete_volume for %s suceeded"
msgstr ""

#: nova/volume/driver.py:843
#, python-format
msgid "\tFE VSA Volume %s local path call - call discover"
msgstr ""

#: nova/volume/driver.py:850 nova/volume/san.py:595
msgid "local_path not supported"
msgstr ""

#: nova/volume/driver.py:858
#, python-format
msgid "\tFE VSA Volume %s ensure export - do nothing"
msgstr ""

#: nova/volume/driver.py:882
#, python-format
msgid "\tFE VSA Volume %s create export - do nothing"
msgstr ""

#: nova/volume/driver.py:902
#, python-format
msgid "\tFE VSA Volume %s remove export - do nothing"
msgstr ""

#: nova/volume/driver.py:922
#, python-format
msgid "VSA BE remove_export for %s failed"
msgstr ""

#: nova/volume/driver.py:974
msgid "Failed to retrieve QoS info"
msgstr ""

#: nova/volume/manager.py:96
#, python-format
msgid "Re-exporting %s volumes"
msgstr "Re-exporting %s volumes"

#: nova/volume/manager.py:101
#, python-format
msgid "volume %s: skipping export"
msgstr "volume %s: skipping export"

#: nova/volume/manager.py:107
#, python-format
msgid "volume %s: creating"
msgstr "volume %s: creating"

#: nova/volume/manager.py:119
#, python-format
msgid "volume %(vol_name)s: creating lv of size %(vol_size)sG"
msgstr "volume %(vol_name)s: creating logical volume of size %(vol_size)sG"

#: nova/volume/manager.py:131
#, python-format
msgid "volume %s: creating export"
msgstr "volume %s: creating export"

#: nova/volume/manager.py:145
#, python-format
msgid "volume %s: created successfully"
msgstr "volume %s: created successfully"

#: nova/volume/manager.py:174
msgid "Volume is still attached"
msgstr "Volume is still attached"

#: nova/volume/manager.py:176
msgid "Volume is not local to this node"
msgstr "Volume is not local to this node"

#: nova/volume/manager.py:180
#, python-format
msgid "volume %s: removing export"
msgstr "volume %s: removing export"

#: nova/volume/manager.py:182
#, python-format
msgid "volume %s: deleting"
msgstr "volume %s: deleting"

#: nova/volume/manager.py:185
#, python-format
msgid "volume %s: volume is busy"
msgstr ""

#: nova/volume/manager.py:197
#, python-format
msgid "volume %s: deleted successfully"
msgstr "volume %s: deleted successfully"

#: nova/volume/manager.py:204
#, python-format
msgid "snapshot %s: creating"
msgstr ""

#: nova/volume/manager.py:208
#, python-format
msgid "snapshot %(snap_name)s: creating"
msgstr ""

#: nova/volume/manager.py:223
#, python-format
msgid "snapshot %s: created successfully"
msgstr ""

#: nova/volume/manager.py:232
#, python-format
msgid "snapshot %s: deleting"
msgstr ""

#: nova/volume/manager.py:235
#, fuzzy, python-format
msgid "snapshot %s: snapshot is busy"
msgstr "instance %s: snapshotting"

#: nova/volume/manager.py:247
#, python-format
msgid "snapshot %s: deleted successfully"
msgstr ""

#: nova/volume/manager.py:329
msgid "Checking volume capabilities"
msgstr ""

#: nova/volume/manager.py:333
#, python-format
msgid "New capabilities found: %s"
msgstr ""

#: nova/volume/manager.py:344
msgid "Clear capabilities"
msgstr ""

#: nova/volume/manager.py:348
#, python-format
msgid "Notification {%s} received"
msgstr ""

#: nova/volume/san.py:114 nova/volume/san.py:152
msgid "Specify san_password or san_private_key"
msgstr ""

#: nova/volume/san.py:157
msgid "san_ip must be set"
msgstr ""

#: nova/volume/san.py:321
#, python-format
msgid "LUID not found for %(zfs_poolname)s. Output=%(out)s"
msgstr ""

#: nova/volume/san.py:453
#, python-format
msgid "CLIQ command returned %s"
msgstr ""

#: nova/volume/san.py:459
#, python-format
msgid "Malformed response to CLIQ command %(verb)s %(cliq_args)s. Result=%(out)s"
msgstr ""

#: nova/volume/san.py:467
#, python-format
msgid "Error running CLIQ command %(verb)s %(cliq_args)s.  Result=%(out)s"
msgstr ""

#: nova/volume/san.py:497
#, python-format
msgid ""
"Unexpected number of virtual ips for cluster  %(cluster_name)s. "
"Result=%(_xml)s"
msgstr ""

#: nova/volume/san.py:550
#, python-format
msgid "Volume info: %(volume_name)s => %(volume_attributes)s"
msgstr ""

#: nova/volume/san.py:627
#, python-format
msgid "Could not determine project for volume %s, can't export"
msgstr ""

#: nova/volume/san.py:697
#, python-format
msgid "Payload for SolidFire API call: %s"
msgstr ""

#: nova/volume/san.py:714
#, python-format
msgid "Call to json.loads() raised an exception: %s"
msgstr ""

#: nova/volume/san.py:719
#, python-format
msgid "Results of SolidFire API call: %s"
msgstr ""

#: nova/volume/san.py:733
#, python-format
msgid "Found solidfire account: %s"
msgstr ""

#: nova/volume/san.py:747
#, python-format
msgid "solidfire account: %s does not exist, create it..."
msgstr ""

#: nova/volume/san.py:805
msgid "Enter SolidFire create_volume..."
msgstr ""

#: nova/volume/san.py:844
msgid "Leaving SolidFire create_volume"
msgstr ""

#: nova/volume/san.py:859
msgid "Enter SolidFire delete_volume..."
msgstr ""

#: nova/volume/san.py:878
#, python-format
msgid "Deleting volumeID: %s "
msgstr ""

#: nova/volume/san.py:886
msgid "Leaving SolidFire delete_volume"
msgstr ""

#: nova/volume/san.py:889
msgid "Executing SolidFire ensure_export..."
msgstr ""

#: nova/volume/san.py:893
msgid "Executing SolidFire create_export..."
msgstr ""

#: nova/volume/volume_types.py:49 nova/volume/volume_types.py:108
msgid "name cannot be None"
msgstr ""

#: nova/volume/volume_types.py:96
msgid "id cannot be None"
msgstr ""

#: nova/volume/xensm.py:55
#, python-format
msgid "SR name = %s"
msgstr ""

#: nova/volume/xensm.py:56
#, python-format
msgid "Params: %s"
msgstr ""

#: nova/volume/xensm.py:60
#, python-format
msgid "Failed to create sr %s...continuing"
msgstr ""

#: nova/volume/xensm.py:62
msgid "Create failed"
msgstr ""

#: nova/volume/xensm.py:64
#, python-format
msgid "SR UUID of new SR is: %s"
msgstr ""

#: nova/volume/xensm.py:71
msgid "Failed to update db"
msgstr ""

#: nova/volume/xensm.py:80
#, python-format
msgid "Failed to introduce sr %s...continuing"
msgstr ""

#: nova/volume/xensm.py:91
#, python-format
msgid "Failed to reach backend %d"
msgstr ""

#: nova/volume/xensm.py:100
msgid "XenSMDriver requires xenapi connection"
msgstr ""

#: nova/volume/xensm.py:110
msgid "Failed to initiate session"
msgstr ""

#: nova/volume/xensm.py:142
#, python-format
msgid "Volume will be created in backend - %d"
msgstr ""

#: nova/volume/xensm.py:154
msgid "Failed to update volume in db"
msgstr ""

#: nova/volume/xensm.py:157
msgid "Unable to create volume"
msgstr ""

#: nova/volume/xensm.py:171
msgid "Failed to delete vdi"
msgstr ""

#: nova/volume/xensm.py:177
msgid "Failed to delete volume in db"
msgstr ""

#: nova/volume/xensm.py:211
msgid "Failed to find volume in db"
msgstr ""

#: nova/volume/xensm.py:222
msgid "Failed to find backend in db"
msgstr ""

#: nova/volume/nexenta/__init__.py:27
msgid "Nexenta SA returned the error"
msgstr ""

#: nova/volume/nexenta/jsonrpc.py:64
#, python-format
msgid "Sending JSON data: %s"
msgstr ""

#: nova/volume/nexenta/jsonrpc.py:69
#, python-format
msgid "Auto switching to HTTPS connection to %s"
msgstr ""

#: nova/volume/nexenta/jsonrpc.py:75
msgid "No headers in server response"
msgstr ""

#: nova/volume/nexenta/jsonrpc.py:76
msgid "Bad response from server"
msgstr ""

#: nova/volume/nexenta/jsonrpc.py:79
#, fuzzy, python-format
msgid "Got response: %s"
msgstr "response %s"

#: nova/volume/nexenta/volume.py:96
#, fuzzy, python-format
msgid "Volume %s does not exist in Nexenta SA"
msgstr "volume group %s doesn't exist"

#: nova/volume/nexenta/volume.py:180
msgid ""
"Call to local_path should not happen. Verify that use_local_volumes flag "
"is turned off."
msgstr ""

#: nova/volume/nexenta/volume.py:202
#, python-format
msgid "Ignored target creation error \"%s\" while ensuring export"
msgstr ""

#: nova/volume/nexenta/volume.py:210
#, python-format
msgid "Ignored target group creation error \"%s\" while ensuring export"
msgstr ""

#: nova/volume/nexenta/volume.py:219
#, python-format
msgid "Ignored target group member addition error \"%s\" while ensuring export"
msgstr ""

#: nova/volume/nexenta/volume.py:227
#, python-format
msgid "Ignored LU creation error \"%s\" while ensuring export"
msgstr ""

#: nova/volume/nexenta/volume.py:237
#, python-format
msgid "Ignored LUN mapping entry addition error \"%s\" while ensuring export"
msgstr ""

#: nova/volume/nexenta/volume.py:273
#, python-format
msgid ""
"Got error trying to destroy target group %(target_group)s, assuming it is"
" already gone: %(exc)s"
msgstr ""

#: nova/volume/nexenta/volume.py:280
#, python-format
msgid ""
"Got error trying to delete target %(target)s, assuming it is already "
"gone: %(exc)s"
msgstr ""

#: nova/vsa/api.py:82
msgid "invalid drive data"
msgstr ""

#: nova/vsa/api.py:105
msgid "drive_name not defined"
msgstr ""

#: nova/vsa/api.py:111
#, python-format
msgid "invalid drive type name %s"
msgstr ""

#: nova/vsa/api.py:155
msgid "*** Experimental VSA code ***"
msgstr ""

#: nova/vsa/api.py:158 nova/vsa/api.py:303
#, python-format
msgid "Requested number of VCs (%d) is too high. Setting to default"
msgstr ""

#: nova/vsa/api.py:194
#, python-format
msgid "Creating VSA: %s"
msgstr ""

#: nova/vsa/api.py:241
#, python-format
msgid ""
"VSA ID %(vsa_id)d %(vsa_name)s: Create volume %(vol_name)s, %(vol_size)d "
"GB, type %(vol_type_id)s"
msgstr ""

#: nova/vsa/api.py:272
#, python-format
msgid "VSA ID %(vsa_id)d: Update VSA status to %(status)s"
msgstr ""

#: nova/vsa/api.py:287
#, python-format
msgid "VSA ID %(vsa_id)d: Update VSA call"
msgstr ""

#: nova/vsa/api.py:318
#, python-format
msgid "Adding %(add_cnt)s VCs to VSA %(vsa_name)s."
msgstr ""

#: nova/vsa/api.py:324
#, python-format
msgid "Deleting %(del_cnt)s VCs from VSA %(vsa_name)s."
msgstr ""

#: nova/vsa/api.py:351
#, python-format
msgid "VSA ID %(vsa_id)s: Deleting %(direction)s volume %(vol_name)s"
msgstr ""

#: nova/vsa/api.py:355
#, python-format
msgid "Unable to delete volume %s"
msgstr ""

#: nova/vsa/api.py:357
#, python-format
msgid "VSA ID %(vsa_id)s: Forced delete. %(direction)s volume %(vol_name)s"
msgstr ""

#: nova/vsa/api.py:363
#, python-format
msgid "Going to try to terminate VSA ID %s"
msgstr ""

#: nova/vsa/api.py:374
#, python-format
msgid "VSA ID %(vsa_id)s: Delete instance %(name)s"
msgstr ""

#: nova/vsa/manager.py:73
#, python-format
msgid "Create call received for VSA %s"
msgstr ""

#: nova/vsa/manager.py:80 nova/vsa/manager.py:107
#, python-format
msgid "Failed to find VSA %(vsa_id)d"
msgstr ""

#: nova/vsa/manager.py:89
#, python-format
msgid "VSA ID %(vsa_id)s: Drive %(vol_id)s created. Status %(status)s"
msgstr ""

#: nova/vsa/manager.py:100
#, python-format
msgid "Drive %(vol_name)s (%(vol_disp_name)s) still in creating phase - wait"
msgstr ""

#: nova/vsa/manager.py:114
#, python-format
msgid ""
"VSA ID %(vsa_id)d: Not all volumes are created (%(cvol_real)d of "
"%(cvol_exp)d)"
msgstr ""

#: nova/vsa/manager.py:137
#, python-format
msgid ""
"VSA ID %(vsa_id)d: Drive %(vol_name)s (%(vol_disp_name)s) is in "
"%(status)s state"
msgstr ""

#: nova/vsa/manager.py:146
#, python-format
msgid "Failed to update attach status for volume %(vol_name)s. %(ex)s"
msgstr ""

#: nova/vsa/manager.py:153
#, python-format
msgid "VSA ID %(vsa_id)d: Delete all BE volumes"
msgstr ""

#: nova/vsa/manager.py:168
#, python-format
msgid "VSA ID %(vsa_id)d: Start %(vc_count)d instances"
msgstr ""

#~ msgid "Going to try to soft delete %s"
#~ msgstr ""

#~ msgid "No host for instance %s, deleting immediately"
#~ msgstr ""

#~ msgid "Going to try to stop %s"
#~ msgstr ""

#~ msgid "Going to try to start %s"
#~ msgstr ""

#~ msgid ""
#~ "Instance %(name)s found in database but"
#~ " not known by hypervisor. Setting "
#~ "power state to NOSTATE"
#~ msgstr ""

#~ msgid ""
#~ "Destroying instance with name label "
#~ "'%(name_label)s' which is marked as "
#~ "DELETED but still present on host."
#~ msgstr ""

#~ msgid "Can't downgrade without losing data"
#~ msgstr ""

#~ msgid "Unable to get updated status: %s"
#~ msgstr ""

#~ msgid ""
#~ "deactivate_node is called for                "
#~ "node_id = %(id)s node_ip = %(ip)s"
#~ msgstr ""

#~ msgid "During wait running, %s disappeared."
#~ msgstr ""

#~ msgid "Instance %s running successfully."
#~ msgstr ""

#~ msgid "The nwfilter(%(instance_secgroup_filter_name)s) is not found."
#~ msgstr ""

#~ msgid ""
#~ "%(container_format)s-%(id)s (%(base_file)s): in: on"
#~ " other nodes (%(remote)d on other "
#~ "nodes)"
#~ msgstr ""

